# Generated by Django 5.1.4 on 2025-09-11 21:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_systemmodule_companymodule_usermodulepermission"),
        ("payroll", "0003_laboratoryspecialty_alter_healthcarerole_category_and_more"),
        ("third_parties", "0004_thirdparty_birth_date_thirdparty_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consultation_date", models.DateTimeField()),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("primera_vez", "Primera Vez"),
                            ("control", "Control"),
                            ("urgencia", "Urgencia"),
                            ("cirugia", "Cirugía"),
                            ("procedimiento", "Procedimiento"),
                            ("interconsulta", "Interconsulta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("in_progress", "En Curso"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("no_show", "No Asistió"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1"))
                        ],
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(220),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("30.0")),
                            django.core.validators.MaxValueValidator(Decimal("45.0")),
                        ],
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("chief_complaint", models.TextField(help_text="Motivo de consulta")),
                (
                    "current_illness",
                    models.TextField(blank=True, help_text="Enfermedad actual"),
                ),
                (
                    "physical_examination",
                    models.TextField(blank=True, help_text="Examen físico"),
                ),
                (
                    "assessment",
                    models.TextField(blank=True, help_text="Impresión diagnóstica"),
                ),
                ("plan", models.TextField(blank=True, help_text="Plan de tratamiento")),
                (
                    "primary_diagnosis_code",
                    models.CharField(
                        blank=True, help_text="Código CIE-10", max_length=10
                    ),
                ),
                (
                    "primary_diagnosis_description",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "secondary_diagnoses",
                    models.TextField(
                        blank=True, help_text="Diagnósticos secundarios (JSON)"
                    ),
                ),
                (
                    "prescriptions",
                    models.TextField(blank=True, help_text="Medicamentos prescritos"),
                ),
                (
                    "lab_orders",
                    models.TextField(blank=True, help_text="Órdenes de laboratorio"),
                ),
                (
                    "imaging_orders",
                    models.TextField(blank=True, help_text="Órdenes de imágenes"),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attending_physician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to="payroll.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "db_table": "medical_consultations",
                "ordering": ["-consultation_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_number", models.CharField(max_length=20, unique=True)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("general", "Medicina General"),
                            ("ginecologia", "Ginecología"),
                            ("laboratorio", "Laboratorio"),
                            ("pediatria", "Pediatría"),
                            ("cardiologia", "Cardiología"),
                            ("neurologia", "Neurología"),
                            ("dermatologia", "Dermatología"),
                            ("oftalmologia", "Oftalmología"),
                            ("otorrinolaringologia", "Otorrinolaringología"),
                            ("urologia", "Urología"),
                            ("traumatologia", "Traumatología"),
                            ("psiquiatria", "Psiquiatría"),
                            ("endocrinologia", "Endocrinología"),
                            ("gastroenterologia", "Gastroenterología"),
                            ("neumologia", "Neumología"),
                            ("reumatologia", "Reumatología"),
                            ("oncologia", "Oncología"),
                            ("cirugia_general", "Cirugía General"),
                            ("anestesiologia", "Anestesiología"),
                            ("radiologia", "Radiología"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activa"),
                            ("inactive", "Inactiva"),
                            ("transferred", "Transferida"),
                            ("closed", "Cerrada"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "opening_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("closing_date", models.DateTimeField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="Alergias conocidas"),
                ),
                (
                    "chronic_conditions",
                    models.TextField(blank=True, help_text="Condiciones crónicas"),
                ),
                (
                    "current_medications",
                    models.TextField(blank=True, help_text="Medicamentos actuales"),
                ),
                (
                    "family_history",
                    models.TextField(blank=True, help_text="Antecedentes familiares"),
                ),
                (
                    "surgical_history",
                    models.TextField(blank=True, help_text="Antecedentes quirúrgicos"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attending_physician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records",
                        to="payroll.employee",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"is_patient": True, "type": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="third_parties.thirdparty",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia Clínica",
                "verbose_name_plural": "Historias Clínicas",
                "db_table": "medical_records",
                "ordering": ["-last_update"],
                "unique_together": {("company", "record_number")},
            },
        ),
        migrations.CreateModel(
            name="MedicalAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("image", "Imagen"),
                            ("document", "Documento"),
                            ("lab_result", "Resultado de Laboratorio"),
                            ("imaging_study", "Estudio de Imagen"),
                            ("prescription", "Prescripción"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="medical_records/%Y/%m/")),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="medical_records.consultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="medical_records.medicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo Adjunto",
                "verbose_name_plural": "Archivos Adjuntos",
                "db_table": "medical_attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="consultation",
            name="medical_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="medical_records.medicalrecord",
            ),
        ),
        migrations.CreateModel(
            name="SpecialtyTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("general", "Medicina General"),
                            ("ginecologia", "Ginecología"),
                            ("laboratorio", "Laboratorio"),
                            ("pediatria", "Pediatría"),
                            ("cardiologia", "Cardiología"),
                            ("neurologia", "Neurología"),
                            ("dermatologia", "Dermatología"),
                            ("oftalmologia", "Oftalmología"),
                            ("otorrinolaringologia", "Otorrinolaringología"),
                            ("urologia", "Urología"),
                            ("traumatologia", "Traumatología"),
                            ("psiquiatria", "Psiquiatría"),
                            ("endocrinologia", "Endocrinología"),
                            ("gastroenterologia", "Gastroenterología"),
                            ("neumologia", "Neumología"),
                            ("reumatologia", "Reumatología"),
                            ("oncologia", "Oncología"),
                            ("cirugia_general", "Cirugía General"),
                            ("anestesiologia", "Anestesiología"),
                            ("radiologia", "Radiología"),
                        ],
                        max_length=30,
                    ),
                ),
                ("chief_complaint_template", models.TextField(blank=True)),
                ("physical_examination_template", models.TextField(blank=True)),
                ("assessment_template", models.TextField(blank=True)),
                ("plan_template", models.TextField(blank=True)),
                (
                    "required_vital_signs",
                    models.JSONField(
                        default=list, help_text="Lista de signos vitales requeridos"
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        default=dict, help_text="Campos personalizados por especialidad"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Especialidad",
                "verbose_name_plural": "Plantillas de Especialidad",
                "db_table": "medical_specialty_templates",
                "unique_together": {("company", "name", "specialty")},
            },
        ),
    ]
