# Generated by Django 5.1.4 on 2025-09-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_default_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="owned_company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa propietaria para usuarios dueño de empresa",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owners",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador del Sistema"),
                    ("contador", "Contador"),
                    ("dueno_empresa", "Dueño de Empresa"),
                    ("auxiliar_contable", "Auxiliar Contable"),
                    ("tesorero", "Tesorero"),
                    ("jefe_nomina", "Jefe de Nómina"),
                    ("auditor", "Auditor"),
                    ("cliente", "Cliente/Proveedor"),
                ],
                default="auxiliar_contable",
                max_length=20,
            ),
        ),
    ]
