# Generated by Django 5.1.4 on 2025-09-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_owned_company_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "Empresa General"),
                    ("salud", "Sector Salud"),
                    ("educacion", "Sector Educación"),
                    ("manufactura", "Manufactura"),
                    ("comercio", "Comercio"),
                    ("servicios", "Servicios"),
                    ("construccion", "Construcción"),
                    ("tecnologia", "Tecnología"),
                    ("transporte", "Transporte"),
                    ("financiero", "Sector Financiero"),
                    ("agropecuario", "Agropecuario"),
                    ("mineria", "Minería y Energía"),
                ],
                default="general",
                help_text="Categoría de empresa para módulos especializados",
                max_length=20,
            ),
        ),
    ]
