# Generated by Django 5.1.4 on 2025-09-11 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_company_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("finance", "Financiero"),
                            ("operations", "Operacional"),
                            ("healthcare", "Sector Salud"),
                            ("education", "Sector Educación"),
                            ("retail", "Retail"),
                            ("manufacturing", "Manufactura"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "url_pattern",
                    models.CharField(
                        help_text="Patrón de URL del módulo (ej: 'gynecology')",
                        max_length=100,
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="bi-puzzle",
                        help_text="Clase CSS del ícono (Bootstrap Icons)",
                        max_length=50,
                    ),
                ),
                (
                    "requires_company_category",
                    models.CharField(
                        blank=True,
                        help_text="Categoría de empresa requerida",
                        max_length=20,
                    ),
                ),
                (
                    "is_core_module",
                    models.BooleanField(
                        default=False,
                        help_text="Módulo core que no se puede desactivar",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Módulo del Sistema",
                "verbose_name_plural": "Módulos del Sistema",
                "db_table": "core_system_modules",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("enabled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_modules",
                        to="core.company",
                    ),
                ),
                (
                    "enabled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.systemmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo de Empresa",
                "verbose_name_plural": "Módulos de Empresa",
                "db_table": "core_company_modules",
                "ordering": ["module__category", "module__name"],
                "unique_together": {("company", "module")},
            },
        ),
        migrations.CreateModel(
            name="UserModulePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("view", "Solo Ver"),
                            ("edit", "Ver y Editar"),
                            ("admin", "Administrador del Módulo"),
                        ],
                        default="view",
                        max_length=10,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.companymodule",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso de Módulo",
                "verbose_name_plural": "Permisos de Módulos",
                "db_table": "core_user_module_permissions",
                "unique_together": {("user", "company_module")},
            },
        ),
    ]
