# Generated by Django 5.1.4 on 2025-09-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_systemmodule_companymodule_usermodulepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmodule",
            name="requires_company_sector",
            field=models.CharField(
                blank=True,
                help_text="Sector de empresa requerido (public/private)",
                max_length=20,
            ),
        ),
    ]
