# Generated by Django 5.1.4 on 2025-09-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_systemmodule_requires_company_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrador"),
                    ("admin", "Administrador/Contador"),
                    ("contador", "Contador"),
                    ("dueno_empresa", "Dueño de Empresa"),
                    ("auxiliar_contable", "Auxiliar Contable"),
                    ("tesorero", "Tesorero"),
                    ("jefe_nomina", "Jefe de Nómina"),
                    ("auditor", "Auditor"),
                    ("cliente", "Cliente/Proveedor"),
                ],
                default="auxiliar_contable",
                max_length=20,
            ),
        ),
    ]
