# Generated by Django 5.1.4 on 2025-10-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercompanypermission",
            name="can_access_billing_health",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercompanypermission",
            name="can_access_diagnostics",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercompanypermission",
            name="can_access_emergency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercompanypermission",
            name="can_access_hospitalization",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercompanypermission",
            name="can_access_medical_records",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercompanypermission",
            name="can_access_patients",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercompanypermission",
            name="can_access_pharmacy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usercompanypermission",
            name="can_access_surgery",
            field=models.BooleanField(default=False),
        ),
    ]
