# Generated by Django 5.1.4 on 2025-09-11 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_company_category"),
        ("payroll", "0002_companycategory_healthcarerole_medicalspecialty_and_more"),
        ("third_parties", "0004_thirdparty_birth_date_thirdparty_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GynecologyConsultationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=30, help_text="Duración estimada en minutos"
                    ),
                ),
                (
                    "requires_preparation",
                    models.BooleanField(
                        default=False, help_text="Requiere preparación especial"
                    ),
                ),
                ("preparation_instructions", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gynecology_consultation_types",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Consulta",
                "verbose_name_plural": "Tipos de Consulta",
                "db_table": "gynecology_consultation_types",
                "ordering": ["name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="GynecologyProcedure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("diagnostico", "Procedimientos Diagnósticos"),
                            ("terapeutico", "Procedimientos Terapéuticos"),
                            ("quirurgico_menor", "Cirugía Menor"),
                            ("quirurgico_mayor", "Cirugía Mayor"),
                            ("ambulatorio", "Procedimientos Ambulatorios"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("requires_anesthesia", models.BooleanField(default=False)),
                ("requires_hospitalization", models.BooleanField(default=False)),
                (
                    "estimated_duration",
                    models.IntegerField(help_text="Duración estimada en minutos"),
                ),
                ("pre_procedure_instructions", models.TextField(blank=True)),
                ("post_procedure_instructions", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gynecology_procedures",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimiento Ginecológico",
                "verbose_name_plural": "Procedimientos Ginecológicos",
                "db_table": "gynecology_procedures",
                "ordering": ["category", "name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="GynecologyAppointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(help_text="Número de cita", max_length=50),
                ),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                (
                    "estimated_duration",
                    models.IntegerField(
                        default=30, help_text="Duración estimada en minutos"
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("consulta", "Consulta Externa"),
                            ("control", "Control"),
                            ("procedimiento", "Procedimiento"),
                            ("cirugia", "Cirugía"),
                            ("urgencia", "Urgencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("chief_complaint", models.TextField(help_text="Motivo de consulta")),
                ("notes", models.TextField(blank=True, help_text="Notas adicionales")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("confirmed", "Confirmada"),
                            ("in_progress", "En Curso"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("no_show", "Inasistencia"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attending_physician",
                    models.ForeignKey(
                        help_text="Médico especialista asignado",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.employee",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gynecology_appointments",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultation_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gynecology.gynecologyconsultationtype",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gynecology.gynecologyprocedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita Ginecológica",
                "verbose_name_plural": "Citas Ginecológicas",
                "db_table": "gynecology_appointments",
                "ordering": ["appointment_date", "appointment_time"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "medical_record_number",
                    models.CharField(
                        help_text="Número de historia clínica", max_length=50
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        choices=[
                            ("eps", "EPS"),
                            ("prepagada", "Medicina Prepagada"),
                            ("particular", "Particular"),
                            ("soat", "SOAT"),
                            ("poliza", "Póliza de Seguros"),
                        ],
                        default="eps",
                        max_length=20,
                    ),
                ),
                (
                    "eps_name",
                    models.CharField(
                        blank=True, help_text="Nombre de la EPS", max_length=200
                    ),
                ),
                (
                    "insurance_number",
                    models.CharField(
                        blank=True, help_text="Número de afiliación", max_length=50
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "pregnancies",
                    models.IntegerField(default=0, help_text="Gestaciones"),
                ),
                ("births", models.IntegerField(default=0, help_text="Partos")),
                ("abortions", models.IntegerField(default=0, help_text="Abortos")),
                (
                    "cesarean_sections",
                    models.IntegerField(default=0, help_text="Cesáreas"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gynecology_patients",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "third_party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to="third_parties.thirdparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "db_table": "gynecology_patients",
                "ordering": ["third_party__first_name", "third_party__last_name"],
                "unique_together": {("company", "medical_record_number")},
            },
        ),
        migrations.CreateModel(
            name="GynecologyMedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "menarche_age",
                    models.IntegerField(
                        blank=True, help_text="Edad de menarquia", null=True
                    ),
                ),
                (
                    "last_menstrual_period",
                    models.DateField(
                        blank=True, help_text="Fecha última menstruación", null=True
                    ),
                ),
                (
                    "menstrual_cycle_days",
                    models.IntegerField(
                        blank=True, help_text="Días del ciclo menstrual", null=True
                    ),
                ),
                ("sexually_active", models.BooleanField(blank=True, null=True)),
                ("contraceptive_method", models.CharField(blank=True, max_length=200)),
                (
                    "obstetric_history",
                    models.TextField(
                        blank=True, help_text="Historia obstétrica detallada"
                    ),
                ),
                ("general_appearance", models.TextField(blank=True)),
                (
                    "vital_signs",
                    models.JSONField(default=dict, help_text="Signos vitales"),
                ),
                (
                    "breast_examination",
                    models.TextField(blank=True, help_text="Examen de mamas"),
                ),
                (
                    "gynecological_examination",
                    models.TextField(blank=True, help_text="Examen ginecológico"),
                ),
                (
                    "clinical_findings",
                    models.TextField(blank=True, help_text="Hallazgos clínicos"),
                ),
                (
                    "primary_diagnosis",
                    models.CharField(help_text="Diagnóstico principal", max_length=500),
                ),
                (
                    "secondary_diagnoses",
                    models.TextField(blank=True, help_text="Diagnósticos secundarios"),
                ),
                (
                    "treatment_plan",
                    models.TextField(blank=True, help_text="Plan de tratamiento"),
                ),
                (
                    "medications",
                    models.TextField(blank=True, help_text="Medicamentos prescritos"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, help_text="Recomendaciones"),
                ),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to="gynecology.gynecologyappointment",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gynecology_medical_records",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="gynecology.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia Clínica Ginecológica",
                "verbose_name_plural": "Historias Clínicas Ginecológicas",
                "db_table": "gynecology_medical_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GynecologyLabResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("citologia", "Citología Cervical"),
                            ("colposcopia", "Colposcopia"),
                            ("biopsia", "Biopsia"),
                            ("ecografia", "Ecografía Ginecológica"),
                            ("hormonal", "Perfil Hormonal"),
                            ("cultivo", "Cultivo Vaginal"),
                            ("marcadores", "Marcadores Tumorales"),
                        ],
                        max_length=20,
                    ),
                ),
                ("study_name", models.CharField(max_length=200)),
                ("study_date", models.DateField()),
                ("results", models.TextField(help_text="Resultados del estudio")),
                (
                    "interpretation",
                    models.TextField(
                        blank=True, help_text="Interpretación del resultado"
                    ),
                ),
                ("is_abnormal", models.BooleanField(default=False)),
                ("requires_follow_up", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gynecology_lab_results",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="gynecology.gynecologymedicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_results",
                        to="gynecology.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Laboratorio",
                "verbose_name_plural": "Resultados de Laboratorio",
                "db_table": "gynecology_lab_results",
                "ordering": ["-study_date"],
            },
        ),
        migrations.AddField(
            model_name="gynecologyappointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="gynecology.patient",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gynecologyappointment",
            unique_together={("company", "appointment_number")},
        ),
    ]
