# Generated by Django 5.1.4 on 2025-10-13 16:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_bank", "0001_initial"),
        ("core", "0008_usercompanypermission_can_access_billing_health_and_more"),
        ("medical_records", "0001_initial"),
        ("payroll", "0003_laboratoryspecialty_alter_healthcarerole_category_and_more"),
        ("third_parties", "0004_thirdparty_birth_date_thirdparty_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("component_code", models.CharField(max_length=50, unique=True)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("whole_blood", "Sangre Total"),
                            ("packed_red_cells", "Glóbulos Rojos Empaquetados"),
                            ("platelet_concentrate", "Concentrado Plaquetario"),
                            ("fresh_frozen_plasma", "Plasma Fresco Congelado"),
                            ("cryoprecipitate", "Crioprecipitado"),
                            ("granulocytes", "Granulocitos"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "volume_ml",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "storage_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Temperatura en °C",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("collection_date", models.DateTimeField()),
                ("expiration_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quarantine", "En Cuarentena"),
                            ("available", "Disponible"),
                            ("reserved", "Reservado"),
                            ("issued", "Despachado"),
                            ("expired", "Vencido"),
                            ("discarded", "Descartado"),
                        ],
                        default="quarantine",
                        max_length=20,
                    ),
                ),
                ("discard_reason", models.TextField(blank=True)),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="Refrigerador/Freezer #, Rack, Posición",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hemocomponente",
                "verbose_name_plural": "Hemocomponentes",
                "db_table": "blood_bank_components",
                "ordering": ["expiration_date"],
            },
        ),
        migrations.CreateModel(
            name="CompatibilityTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("abo_rh", "ABO/Rh"),
                            ("crossmatch", "Prueba Cruzada (Crossmatch)"),
                            ("antibody_screen", "Rastreo de Anticuerpos"),
                            ("direct_coombs", "Coombs Directo"),
                            ("indirect_coombs", "Coombs Indirecto"),
                        ],
                        max_length=30,
                    ),
                ),
                ("test_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("compatible", "Compatible"),
                            ("incompatible", "Incompatible"),
                            ("pending", "Pendiente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blood_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compatibility_tests",
                        to="blood_bank.bloodcomponent",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"is_patient": True, "type": "customer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="third_parties.thirdparty",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compatibility_tests_performed",
                        to="payroll.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prueba de Compatibilidad",
                "verbose_name_plural": "Pruebas de Compatibilidad",
                "db_table": "blood_bank_compatibility_tests",
                "ordering": ["-test_date"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("donation_number", models.CharField(max_length=50, unique=True)),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("whole_blood", "Sangre Total"),
                            ("plateletpheresis", "Plaquetaféresis"),
                            ("plasmapheresis", "Plasmaféresis"),
                            ("double_red_cell", "Doble Glóbulo Rojo"),
                        ],
                        default="whole_blood",
                        max_length=30,
                    ),
                ),
                (
                    "donation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("in_process", "En Proceso"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("adverse_reaction", "Reacción Adversa"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("30.0"))
                        ],
                    ),
                ),
                (
                    "hemoglobin",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hemoglobina en g/dL",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("blood_pressure_systolic", models.IntegerField(blank=True, null=True)),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, null=True),
                ),
                ("pulse", models.IntegerField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("pre_donation_approved", models.BooleanField(default=False)),
                ("pre_donation_notes", models.TextField(blank=True)),
                (
                    "volume_ml",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(500),
                        ],
                    ),
                ),
                ("adverse_reaction", models.BooleanField(default=False)),
                ("adverse_reaction_description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phlebotomist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations_performed",
                        to="payroll.employee",
                    ),
                ),
                (
                    "supervising_physician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donations_supervised",
                        to="payroll.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donación",
                "verbose_name_plural": "Donaciones",
                "db_table": "blood_bank_donations",
                "ordering": ["-donation_date"],
            },
        ),
        migrations.AddField(
            model_name="bloodcomponent",
            name="donation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="components",
                to="blood_bank.donation",
            ),
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(blank=True, max_length=20)),
                ("document_number", models.CharField(blank=True, max_length=50)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("donor_code", models.CharField(max_length=50, unique=True)),
                (
                    "donor_type",
                    models.CharField(
                        choices=[
                            ("voluntary", "Voluntario"),
                            ("directed", "Dirigido"),
                            ("autologous", "Autólogo"),
                        ],
                        default="voluntary",
                        max_length=20,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "rh_factor",
                    models.CharField(
                        choices=[("positive", "Positivo"), ("negative", "Negativo")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("suspended", "Suspendido Temporalmente"),
                            ("permanently_deferred", "Diferido Permanente"),
                            ("inactive", "Inactivo"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("deferral_reason", models.TextField(blank=True)),
                ("deferral_end_date", models.DateField(blank=True, null=True)),
                ("total_donations", models.IntegerField(default=0)),
                ("last_donation_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="donors_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "third_party",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si el donante está registrado en el sistema",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="third_parties.thirdparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donante",
                "verbose_name_plural": "Donantes",
                "db_table": "blood_bank_donors",
                "ordering": ["-last_donation_date"],
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donations",
                to="blood_bank.donor",
            ),
        ),
        migrations.CreateModel(
            name="ScreeningTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("hiv", "VIH"),
                            ("hepatitis_b", "Hepatitis B (HBsAg)"),
                            ("hepatitis_c", "Hepatitis C (Anti-HCV)"),
                            ("syphilis", "Sífilis (VDRL/RPR)"),
                            ("chagas", "Chagas (T. cruzi)"),
                            ("htlv", "HTLV I/II"),
                        ],
                        max_length=30,
                    ),
                ),
                ("test_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("negative", "Negativo"),
                            ("positive", "Positivo"),
                            ("indeterminate", "Indeterminado"),
                            ("pending", "Pendiente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_value", models.CharField(blank=True, max_length=100)),
                ("result_notes", models.TextField(blank=True)),
                ("equipment_used", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_tests",
                        to="blood_bank.donation",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="screening_tests_performed",
                        to="payroll.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prueba de Cribado",
                "verbose_name_plural": "Pruebas de Cribado",
                "db_table": "blood_bank_screening_tests",
                "ordering": ["-test_date"],
                "unique_together": {("donation", "test_type")},
            },
        ),
        migrations.CreateModel(
            name="Transfusion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transfusion_number", models.CharField(max_length=50, unique=True)),
                (
                    "indication",
                    models.TextField(help_text="Indicación médica para la transfusión"),
                ),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordenada"),
                            ("prepared", "Preparada"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completada"),
                            ("stopped", "Detenida"),
                            ("adverse_reaction", "Reacción Adversa"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                ("adverse_reaction", models.BooleanField(default=False)),
                ("adverse_reaction_type", models.CharField(blank=True, max_length=200)),
                ("adverse_reaction_description", models.TextField(blank=True)),
                ("adverse_reaction_management", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administering_nurse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusions_administered",
                        to="payroll.employee",
                    ),
                ),
                (
                    "blood_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusions",
                        to="blood_bank.bloodcomponent",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medical_records.medicalrecord",
                    ),
                ),
                (
                    "ordering_physician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusions_ordered",
                        to="payroll.employee",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"is_patient": True, "type": "customer"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfusions",
                        to="third_parties.thirdparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfusión",
                "verbose_name_plural": "Transfusiones",
                "db_table": "blood_bank_transfusions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Blood_bankModule",
        ),
    ]
