# Generated by Django 5.1.4 on 2025-10-16 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing_health",
            "0002_healthinvoice_healthinvoiceitem_healthpayment_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthinvoiceitem",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="Tipo de Servicio Original",
            ),
        ),
        migrations.AddField(
            model_name="healthinvoiceitem",
            name="object_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID del Servicio Original"
            ),
        ),
    ]
