# Generated by Django 5.1.4 on 2025-09-11 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laborder",
            name="gynecology_appointment",
        ),
    ]
