# Generated by Django 4.2.23 on 2025-08-28 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('vat', 'IVA'), ('withholding_source', 'Retención en la Fuente'), ('withholding_vat', 'Retención de IVA'), ('withholding_ica', 'Retención de ICA'), ('ica', 'Impuesto de Industria y Comercio'), ('income_tax', 'Impuesto de Renta'), ('wealth_tax', 'Impuesto al Patrimonio'), ('other', 'Otro')], max_length=30)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tarifa del impuesto (%)', max_digits=8)),
                ('is_percentage', models.BooleanField(default=True)),
                ('minimum_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maximum_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dian_code', models.CharField(blank=True, help_text='Código DIAN', max_length=10)),
                ('form_line', models.CharField(blank=True, help_text='Línea en formulario', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_payable', to='accounting.account')),
                ('account_receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_receivable', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_types', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Impuesto',
                'verbose_name_plural': 'Tipos de Impuesto',
                'db_table': 'taxes_types',
                'ordering': ['category', 'code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('obligation_type', models.CharField(choices=[('vat_declaration', 'Declaración IVA'), ('vat_payment', 'Pago IVA'), ('income_declaration', 'Declaración Renta'), ('income_payment', 'Pago Renta'), ('withholding_declaration', 'Declaración Retenciones'), ('withholding_payment', 'Pago Retenciones'), ('ica_declaration', 'Declaración ICA'), ('ica_payment', 'Pago ICA'), ('other', 'Otra Obligación')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField(blank=True, null=True)),
                ('period_number', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('extended_due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('last_digit_nit', models.CharField(blank=True, help_text='Último dígito del NIT', max_length=1)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calendar', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendario Tributario',
                'verbose_name_plural': 'Calendario Tributario',
                'db_table': 'taxes_calendar',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['company', 'due_date'], name='taxes_calen_company_d15856_idx'), models.Index(fields=['obligation_type', 'period_year'], name='taxes_calen_obligat_80d7e8_idx')],
            },
        ),
    ]
