# Generated by Django 5.1.4 on 2025-10-15 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_usercompanypermission_can_access_billing_health_and_more"),
        ("occupational_health", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de reporte"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("consolidado_examenes", "Consolidado de Exámenes"),
                            ("ausentismo", "Ausentismo Laboral"),
                            ("accidentalidad", "Accidentalidad"),
                            ("morbilidad", "Morbilidad"),
                            ("riesgos_identificados", "Riesgos Identificados"),
                            ("aptitudes", "Aptitudes Laborales"),
                            ("seguimiento", "Seguimiento y Control"),
                            ("estadistico", "Estadístico"),
                            ("personalizado", "Personalizado"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de reporte",
                    ),
                ),
                (
                    "report_title",
                    models.CharField(max_length=200, verbose_name="Título del reporte"),
                ),
                ("period_start", models.DateField(verbose_name="Período desde")),
                ("period_end", models.DateField(verbose_name="Período hasta")),
                (
                    "client_company",
                    models.CharField(
                        blank=True,
                        help_text="Empresa para la que se genera el reporte",
                        max_length=200,
                        verbose_name="Empresa cliente",
                    ),
                ),
                (
                    "work_area_filter",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Filtro por área"
                    ),
                ),
                (
                    "job_position_filter",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Filtro por cargo"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="Resumen ejecutivo"),
                ),
                (
                    "findings",
                    models.TextField(blank=True, verbose_name="Hallazgos principales"),
                ),
                (
                    "statistics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Estadísticas"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, verbose_name="Recomendaciones generales"
                    ),
                ),
                (
                    "conclusions",
                    models.TextField(blank=True, verbose_name="Conclusiones"),
                ),
                (
                    "attachments_description",
                    models.TextField(blank=True, verbose_name="Descripción de anexos"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("generado", "Generado"),
                            ("enviado", "Enviado"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "generated_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de generación"
                    ),
                ),
                (
                    "sent_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Destinatario"
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupational_reports",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occupational_reports_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte Empresarial",
                "verbose_name_plural": "Reportes Empresariales",
                "db_table": "occupational_health_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OccupationalExam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exam_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Examen"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Empresa donde trabaja el paciente",
                        max_length=200,
                        verbose_name="Empresa empleadora",
                    ),
                ),
                (
                    "job_position",
                    models.CharField(max_length=200, verbose_name="Cargo"),
                ),
                (
                    "work_area",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Área de trabajo"
                    ),
                ),
                (
                    "years_in_position",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Años en el cargo",
                    ),
                ),
                (
                    "work_schedule",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Horario laboral"
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("ingreso", "Examen de Ingreso"),
                            ("periodico", "Examen Periódico"),
                            ("retiro", "Examen de Retiro"),
                            ("reingreso", "Examen de Reingreso"),
                            ("cambio_ocupacion", "Cambio de Ocupación"),
                            ("post_incapacidad", "Post-Incapacidad"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de examen",
                    ),
                ),
                (
                    "exam_date",
                    models.DateTimeField(verbose_name="Fecha y hora del examen"),
                ),
                (
                    "previous_jobs",
                    models.TextField(
                        blank=True,
                        help_text="Historia laboral previa",
                        verbose_name="Trabajos anteriores",
                    ),
                ),
                (
                    "occupational_exposures",
                    models.TextField(
                        blank=True,
                        help_text="Físicas, químicas, biológicas, ergonómicas, psicosociales",
                        verbose_name="Exposiciones ocupacionales",
                    ),
                ),
                (
                    "use_of_ppe",
                    models.TextField(
                        blank=True,
                        help_text="Elementos de protección personal utilizados",
                        verbose_name="Uso de EPP",
                    ),
                ),
                (
                    "personal_medical_history",
                    models.TextField(
                        blank=True, verbose_name="Antecedentes médicos personales"
                    ),
                ),
                (
                    "family_medical_history",
                    models.TextField(
                        blank=True, verbose_name="Antecedentes médicos familiares"
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(blank=True, verbose_name="Medicación actual"),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="Alergias")),
                (
                    "smoking",
                    models.CharField(
                        blank=True,
                        help_text="Sí/No, cantidad",
                        max_length=50,
                        verbose_name="Tabaquismo",
                    ),
                ),
                (
                    "alcohol",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Consumo de alcohol"
                    ),
                ),
                (
                    "physical_activity",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Actividad física"
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Presión arterial"
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Frecuencia cardíaca"
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Frecuencia respiratoria"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Temperatura (°C)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Talla (cm)",
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="IMC",
                    ),
                ),
                (
                    "head_neck_exam",
                    models.TextField(blank=True, verbose_name="Cabeza y cuello"),
                ),
                (
                    "cardiovascular_exam",
                    models.TextField(blank=True, verbose_name="Cardiovascular"),
                ),
                (
                    "respiratory_exam",
                    models.TextField(blank=True, verbose_name="Respiratorio"),
                ),
                (
                    "abdominal_exam",
                    models.TextField(blank=True, verbose_name="Abdominal"),
                ),
                (
                    "musculoskeletal_exam",
                    models.TextField(blank=True, verbose_name="Osteomuscular"),
                ),
                (
                    "neurological_exam",
                    models.TextField(blank=True, verbose_name="Neurológico"),
                ),
                (
                    "dermatological_exam",
                    models.TextField(blank=True, verbose_name="Piel y anexos"),
                ),
                (
                    "laboratory_tests_ordered",
                    models.TextField(
                        blank=True, verbose_name="Laboratorios solicitados"
                    ),
                ),
                (
                    "imaging_studies_ordered",
                    models.TextField(blank=True, verbose_name="Imágenes solicitadas"),
                ),
                (
                    "other_tests_ordered",
                    models.TextField(
                        blank=True, verbose_name="Otros exámenes solicitados"
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Diagnóstico")),
                (
                    "findings",
                    models.TextField(blank=True, verbose_name="Hallazgos relevantes"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en_proceso", "En Proceso"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="programado",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, verbose_name="Observaciones generales"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupational_exams",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occupational_exams_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "examiner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occupational_exams_as_examiner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Médico examinador",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occupational_exams",
                        to="patients.patient",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen Ocupacional",
                "verbose_name_plural": "Exámenes Ocupacionales",
                "db_table": "occupational_health_exam",
                "ordering": ["-exam_date"],
            },
        ),
        migrations.CreateModel(
            name="LaboratoryTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("hematologia", "Hematología Completa"),
                            ("glicemia", "Glicemia"),
                            ("perfil_lipidico", "Perfil Lipídico"),
                            ("creatinina", "Creatinina"),
                            ("parcial_orina", "Parcial de Orina"),
                            ("colinesterasa", "Colinesterasa"),
                            ("espirometria", "Espirometría"),
                            ("audiometria", "Audiometría"),
                            ("visiometria", "Visiometría"),
                            ("rayos_x", "Rayos X"),
                            ("electrocardiograma", "Electrocardiograma"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de examen",
                    ),
                ),
                (
                    "test_name",
                    models.CharField(max_length=200, verbose_name="Nombre del examen"),
                ),
                ("test_date", models.DateField(verbose_name="Fecha de realización")),
                (
                    "result_value",
                    models.TextField(blank=True, verbose_name="Resultado"),
                ),
                (
                    "result_status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("normal", "Normal"),
                            ("alterado", "Alterado"),
                            ("critico", "Crítico"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado del resultado",
                    ),
                ),
                (
                    "reference_values",
                    models.TextField(blank=True, verbose_name="Valores de referencia"),
                ),
                (
                    "interpretation",
                    models.TextField(blank=True, verbose_name="Interpretación"),
                ),
                (
                    "laboratory_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Laboratorio"
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Realizado por"
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupational_lab_tests",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_tests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratory_tests",
                        to="occupational_health.occupationalexam",
                        verbose_name="Examen ocupacional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen de Laboratorio",
                "verbose_name_plural": "Exámenes de Laboratorio",
                "db_table": "occupational_health_lab_test",
                "ordering": ["-test_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("ergonomica", "Ergonómica"),
                            ("higiene_industrial", "Higiene Industrial"),
                            ("seguridad", "Seguridad"),
                            ("medicina_preventiva", "Medicina Preventiva"),
                            ("estilos_vida", "Estilos de Vida Saludable"),
                        ],
                        max_length=30,
                        verbose_name="Categoría",
                    ),
                ),
                ("recommendation", models.TextField(verbose_name="Recomendación")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "implementation_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Plazo de implementación"
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Responsable"
                    ),
                ),
                (
                    "implemented",
                    models.BooleanField(default=False, verbose_name="Implementada"),
                ),
                (
                    "implementation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de implementación"
                    ),
                ),
                (
                    "implementation_notes",
                    models.TextField(
                        blank=True, verbose_name="Notas de implementación"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_recommendations",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_recommendations",
                        to="occupational_health.occupationalexam",
                        verbose_name="Examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recomendación de Salud",
                "verbose_name_plural": "Recomendaciones de Salud",
                "db_table": "occupational_health_recommendation",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OccupationalRisk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("fisico", "Físico"),
                            ("quimico", "Químico"),
                            ("biologico", "Biológico"),
                            ("ergonomico", "Ergonómico"),
                            ("psicosocial", "Psicosocial"),
                            ("mecanico", "Mecánico"),
                            ("electrico", "Eléctrico"),
                            ("locativo", "Locativo"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de riesgo",
                    ),
                ),
                (
                    "risk_description",
                    models.TextField(verbose_name="Descripción del riesgo"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("bajo", "Bajo"),
                            ("medio", "Medio"),
                            ("alto", "Alto"),
                            ("muy_alto", "Muy Alto"),
                        ],
                        max_length=20,
                        verbose_name="Nivel de riesgo",
                    ),
                ),
                (
                    "exposure_time",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tiempo de exposición"
                    ),
                ),
                (
                    "control_measures",
                    models.TextField(
                        blank=True, verbose_name="Medidas de control existentes"
                    ),
                ),
                (
                    "recommended_controls",
                    models.TextField(blank=True, verbose_name="Controles recomendados"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupational_risks",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risks_identified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupational_risks",
                        to="occupational_health.occupationalexam",
                        verbose_name="Examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riesgo Ocupacional",
                "verbose_name_plural": "Riesgos Ocupacionales",
                "db_table": "occupational_health_risk",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkAptitude",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "aptitude_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de concepto"
                    ),
                ),
                (
                    "aptitude",
                    models.CharField(
                        choices=[
                            ("apto", "Apto"),
                            ("apto_con_restricciones", "Apto con Restricciones"),
                            ("apto_con_recomendaciones", "Apto con Recomendaciones"),
                            ("no_apto_temporal", "No Apto Temporal"),
                            ("no_apto_permanente", "No Apto Permanente"),
                            ("aplazado", "Aplazado"),
                        ],
                        max_length=30,
                        verbose_name="Aptitud laboral",
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Fecha de emisión")),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigencia hasta"
                    ),
                ),
                (
                    "restrictions",
                    models.TextField(
                        blank=True,
                        help_text="Limitaciones específicas para el trabajo",
                        verbose_name="Restricciones laborales",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Recomendaciones médicas y de salud ocupacional",
                        verbose_name="Recomendaciones",
                    ),
                ),
                (
                    "requires_follow_up",
                    models.BooleanField(
                        default=False, verbose_name="Requiere seguimiento"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de seguimiento"
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(blank=True, verbose_name="Notas de seguimiento"),
                ),
                (
                    "medical_justification",
                    models.TextField(verbose_name="Justificación médica del concepto"),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, verbose_name="Observaciones adicionales"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_aptitudes",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aptitudes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_aptitude",
                        to="occupational_health.occupationalexam",
                        verbose_name="Examen ocupacional",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aptitudes_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Emitido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aptitud Laboral",
                "verbose_name_plural": "Aptitudes Laborales",
                "db_table": "occupational_health_aptitude",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.DeleteModel(
            name="Occupational_healthModule",
        ),
        migrations.AddIndex(
            model_name="companyreport",
            index=models.Index(
                fields=["company", "report_type"], name="occupationa_company_997ab8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyreport",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="occupationa_period__85e757_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="occupationalexam",
            index=models.Index(
                fields=["company", "exam_type"], name="occupationa_company_565160_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="occupationalexam",
            index=models.Index(
                fields=["patient", "exam_date"], name="occupationa_patient_fc9e8a_idx"
            ),
        ),
    ]
