# Generated by Django 5.1.4 on 2025-10-15 20:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_usercompanypermission_can_access_billing_health_and_more"),
        ("patients", "0001_initial"),
        ("rehabilitation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RehabilitationConsultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consultation_number", models.CharField(max_length=50, unique=True)),
                (
                    "consultation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "chief_complaint",
                    models.TextField(verbose_name="Motivo de consulta"),
                ),
                (
                    "injury_mechanism",
                    models.TextField(blank=True, verbose_name="Mecanismo de lesión"),
                ),
                (
                    "onset_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de inicio de síntomas",
                    ),
                ),
                (
                    "pain_level",
                    models.IntegerField(
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        default=0,
                        verbose_name="Nivel de dolor (0-10)",
                    ),
                ),
                (
                    "pain_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ubicación del dolor"
                    ),
                ),
                (
                    "pain_description",
                    models.TextField(blank=True, verbose_name="Descripción del dolor"),
                ),
                (
                    "medical_history",
                    models.TextField(blank=True, verbose_name="Antecedentes médicos"),
                ),
                (
                    "surgical_history",
                    models.TextField(
                        blank=True, verbose_name="Antecedentes quirúrgicos"
                    ),
                ),
                (
                    "medications",
                    models.TextField(blank=True, verbose_name="Medicamentos actuales"),
                ),
                (
                    "previous_treatments",
                    models.TextField(blank=True, verbose_name="Tratamientos previos"),
                ),
                (
                    "functional_limitations",
                    models.TextField(
                        blank=True, verbose_name="Limitaciones funcionales"
                    ),
                ),
                (
                    "physical_exam_findings",
                    models.TextField(
                        blank=True, verbose_name="Hallazgos del examen físico"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(verbose_name="Diagnóstico fisioterapéutico"),
                ),
                (
                    "treatment_goals",
                    models.TextField(
                        blank=True, verbose_name="Objetivos del tratamiento"
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehab_consultations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehabilitation_consultations",
                        to="patients.patient",
                    ),
                ),
                (
                    "physiotherapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehab_consultations_as_therapist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta de Rehabilitación",
                "verbose_name_plural": "Consultas de Rehabilitación",
                "db_table": "rehabilitation_consultation",
                "ordering": ["-consultation_date"],
            },
        ),
        migrations.CreateModel(
            name="PhysicalAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "posture_analysis",
                    models.TextField(blank=True, verbose_name="Análisis postural"),
                ),
                (
                    "gait_analysis",
                    models.TextField(blank=True, verbose_name="Análisis de marcha"),
                ),
                (
                    "range_of_motion_findings",
                    models.TextField(blank=True, verbose_name="Hallazgos de ROM"),
                ),
                (
                    "muscle_strength_findings",
                    models.TextField(
                        blank=True, verbose_name="Evaluación de fuerza muscular"
                    ),
                ),
                (
                    "flexibility_assessment",
                    models.TextField(
                        blank=True, verbose_name="Evaluación de flexibilidad"
                    ),
                ),
                (
                    "balance_assessment",
                    models.TextField(blank=True, verbose_name="Evaluación de balance"),
                ),
                (
                    "coordination_assessment",
                    models.TextField(
                        blank=True, verbose_name="Evaluación de coordinación"
                    ),
                ),
                (
                    "palpation_findings",
                    models.TextField(blank=True, verbose_name="Hallazgos de palpación"),
                ),
                (
                    "special_tests_performed",
                    models.TextField(
                        blank=True, verbose_name="Pruebas especiales realizadas"
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="physical_assessments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="physical_assessment",
                        to="rehabilitation.rehabilitationconsultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación Física",
                "verbose_name_plural": "Evaluaciones Físicas",
                "db_table": "rehabilitation_physical_assessment",
            },
        ),
        migrations.CreateModel(
            name="RehabilitationPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_number", models.CharField(max_length=50, unique=True)),
                ("plan_date", models.DateField(default=django.utils.timezone.now)),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha estimada de finalización",
                    ),
                ),
                ("diagnosis", models.TextField(verbose_name="Diagnóstico")),
                (
                    "short_term_goals",
                    models.TextField(verbose_name="Objetivos a corto plazo"),
                ),
                (
                    "long_term_goals",
                    models.TextField(verbose_name="Objetivos a largo plazo"),
                ),
                (
                    "treatment_modalities",
                    models.TextField(
                        help_text="Calor, frío, ultrasonido, TENS, láser, electroterapia, etc.",
                        verbose_name="Modalidades terapéuticas",
                    ),
                ),
                (
                    "manual_therapy_techniques",
                    models.TextField(
                        blank=True,
                        help_text="Masaje, movilizaciones, manipulaciones, etc.",
                        verbose_name="Técnicas de terapia manual",
                    ),
                ),
                (
                    "therapeutic_exercises_description",
                    models.TextField(
                        blank=True,
                        verbose_name="Descripción de ejercicios terapéuticos",
                    ),
                ),
                (
                    "frequency_per_week",
                    models.IntegerField(default=3, verbose_name="Sesiones por semana"),
                ),
                (
                    "estimated_sessions",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número estimado de sesiones totales",
                    ),
                ),
                (
                    "precautions",
                    models.TextField(blank=True, verbose_name="Precauciones"),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, verbose_name="Contraindicaciones"),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("completed", "Completado"),
                            ("discontinued", "Discontinuado"),
                            ("on_hold", "En pausa"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rehabilitation_plans",
                        to="rehabilitation.rehabilitationconsultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehab_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehabilitation_plans",
                        to="patients.patient",
                    ),
                ),
                (
                    "physiotherapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehab_plans_as_therapist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Rehabilitación",
                "verbose_name_plural": "Planes de Rehabilitación",
                "db_table": "rehabilitation_plan",
                "ordering": ["-plan_date"],
            },
        ),
        migrations.CreateModel(
            name="ProgressMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "measurement_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "pain_level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        null=True,
                        verbose_name="Nivel de dolor actual (0-10)",
                    ),
                ),
                (
                    "rom_measurements",
                    models.TextField(
                        blank=True,
                        help_text="Ej: Flexión de hombro: 150°, Extensión de rodilla: 0°",
                        verbose_name="Mediciones de rango de movimiento",
                    ),
                ),
                (
                    "strength_measurements",
                    models.TextField(
                        blank=True,
                        help_text="Ej: Cuádriceps 4/5, Bíceps 5/5",
                        verbose_name="Mediciones de fuerza",
                    ),
                ),
                (
                    "functional_tests_results",
                    models.TextField(
                        blank=True,
                        help_text="Ej: Test de marcha de 6 minutos: 450m",
                        verbose_name="Resultados de pruebas funcionales",
                    ),
                ),
                (
                    "patient_reported_improvement",
                    models.IntegerField(
                        blank=True,
                        help_text="0-100%",
                        null=True,
                        verbose_name="Mejoría reportada por paciente (%)",
                    ),
                ),
                (
                    "therapist_assessment",
                    models.TextField(
                        blank=True, verbose_name="Evaluación del terapeuta"
                    ),
                ),
                (
                    "objective_progress_notes",
                    models.TextField(
                        blank=True, verbose_name="Notas objetivas de progreso"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_measurements_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "measured_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_measurements_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_measurements",
                        to="rehabilitation.rehabilitationplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medición de Progreso",
                "verbose_name_plural": "Mediciones de Progreso",
                "db_table": "rehabilitation_progress_measurement",
                "ordering": ["-measurement_date"],
            },
        ),
        migrations.CreateModel(
            name="ExercisePrescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exercise_name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del ejercicio"
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("stretching", "Estiramiento"),
                            ("strengthening", "Fortalecimiento"),
                            ("balance", "Equilibrio/Balance"),
                            ("cardio", "Cardiovascular"),
                            ("functional", "Funcional"),
                            ("proprioception", "Propiocepción"),
                            ("coordination", "Coordinación"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de ejercicio",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción detallada")),
                (
                    "sets",
                    models.IntegerField(blank=True, null=True, verbose_name="Series"),
                ),
                (
                    "repetitions",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Repeticiones"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duración (segundos)"
                    ),
                ),
                (
                    "frequency_per_day",
                    models.IntegerField(default=1, verbose_name="Veces por día"),
                ),
                (
                    "days_per_week",
                    models.IntegerField(default=3, verbose_name="Días por semana"),
                ),
                (
                    "resistance_level",
                    models.CharField(
                        blank=True,
                        help_text="Ej: banda elástica roja, 5kg, peso corporal",
                        max_length=100,
                        verbose_name="Nivel de resistencia",
                    ),
                ),
                (
                    "progression_criteria",
                    models.TextField(
                        blank=True,
                        help_text="Cuándo y cómo aumentar la dificultad",
                        verbose_name="Criterios de progresión",
                    ),
                ),
                (
                    "precautions",
                    models.TextField(
                        blank=True, verbose_name="Precauciones específicas"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Ejercicio activo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exercises_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="rehabilitation.rehabilitationplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescripción de Ejercicio",
                "verbose_name_plural": "Prescripciones de Ejercicios",
                "db_table": "rehabilitation_exercise_prescription",
                "ordering": ["exercise_type", "exercise_name"],
            },
        ),
        migrations.CreateModel(
            name="RehabilitationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_number", models.CharField(max_length=50, unique=True)),
                (
                    "session_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "session_duration",
                    models.IntegerField(default=60, verbose_name="Duración (minutos)"),
                ),
                (
                    "session_number_in_plan",
                    models.IntegerField(default=1, verbose_name="Número de sesión"),
                ),
                (
                    "pain_level_pre",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        null=True,
                        verbose_name="Dolor pre-sesión (0-10)",
                    ),
                ),
                (
                    "pain_level_post",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        null=True,
                        verbose_name="Dolor post-sesión (0-10)",
                    ),
                ),
                (
                    "modalities_applied",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de modalidades físicas aplicadas",
                        verbose_name="Modalidades aplicadas",
                    ),
                ),
                (
                    "manual_therapy_performed",
                    models.TextField(
                        blank=True, verbose_name="Terapia manual realizada"
                    ),
                ),
                (
                    "exercises_performed",
                    models.TextField(blank=True, verbose_name="Ejercicios realizados"),
                ),
                (
                    "patient_tolerance",
                    models.TextField(
                        blank=True,
                        help_text="Cómo toleró el paciente la sesión",
                        verbose_name="Tolerancia del paciente",
                    ),
                ),
                (
                    "patient_response",
                    models.TextField(
                        blank=True,
                        help_text="Respuesta observada durante y después de la sesión",
                        verbose_name="Respuesta del paciente",
                    ),
                ),
                (
                    "homework_assigned",
                    models.TextField(
                        blank=True,
                        verbose_name="Ejercicios/tareas asignadas para el hogar",
                    ),
                ),
                (
                    "next_session_goals",
                    models.TextField(
                        blank=True, verbose_name="Objetivos para próxima sesión"
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("no_show", "No asistió"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehab_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehabilitation_sessions",
                        to="patients.patient",
                    ),
                ),
                (
                    "physiotherapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rehab_sessions_as_therapist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="rehabilitation.rehabilitationplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Rehabilitación",
                "verbose_name_plural": "Sesiones de Rehabilitación",
                "db_table": "rehabilitation_session",
                "ordering": ["-session_date"],
            },
        ),
        migrations.DeleteModel(
            name="RehabilitationModule",
        ),
    ]
