# Generated by Django 5.1.4 on 2025-10-12 18:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_usercompanypermission_can_access_billing_health_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CIE10Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código del capítulo (I, II, III, etc.)",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "code_range_start",
                    models.CharField(
                        help_text="Código inicial del rango (ej: A00)", max_length=10
                    ),
                ),
                (
                    "code_range_end",
                    models.CharField(
                        help_text="Código final del rango (ej: B99)", max_length=10
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Capítulo CIE-10",
                "verbose_name_plural": "Capítulos CIE-10",
                "db_table": "diagnostics_cie10_chapters",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="CIE10Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_range_start", models.CharField(max_length=10)),
                ("code_range_end", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=300)),
                ("order", models.IntegerField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="diagnostics.cie10chapter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo CIE-10",
                "verbose_name_plural": "Grupos CIE-10",
                "db_table": "diagnostics_cie10_groups",
                "ordering": ["order", "code_range_start"],
            },
        ),
        migrations.CreateModel(
            name="CIE10Version",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_code",
                    models.CharField(
                        help_text="Código de versión (ej: CIE10-2023)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Versión actual en uso"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión CIE-10",
                "verbose_name_plural": "Versiones CIE-10",
                "db_table": "diagnostics_cie10_versions",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="CIE10Diagnosis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Código CIE-10 (ej: A00.0)",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descripción del diagnóstico", max_length=500
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=0,
                        help_text="Nivel en la jerarquía (3=categoría, 4=subcategoría)",
                    ),
                ),
                (
                    "is_category",
                    models.BooleanField(
                        default=False, help_text="Es categoría (3 caracteres)"
                    ),
                ),
                (
                    "is_subcategory",
                    models.BooleanField(
                        default=False, help_text="Es subcategoría (4+ caracteres)"
                    ),
                ),
                (
                    "applicable_gender",
                    models.CharField(
                        choices=[("A", "Ambos"), ("M", "Masculino"), ("F", "Femenino")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "min_age_days",
                    models.IntegerField(
                        blank=True, help_text="Edad mínima en días", null=True
                    ),
                ),
                (
                    "max_age_days",
                    models.IntegerField(
                        blank=True, help_text="Edad máxima en días", null=True
                    ),
                ),
                ("includes", models.TextField(blank=True, help_text="Incluye")),
                ("excludes", models.TextField(blank=True, help_text="Excluye")),
                ("notes", models.TextField(blank=True, help_text="Notas adicionales")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "use_count",
                    models.IntegerField(default=0, help_text="Contador de uso"),
                ),
                (
                    "search_vector",
                    models.TextField(
                        blank=True, help_text="Vector de búsqueda normalizado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diagnostics.cie10chapter",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="diagnostics.cie10diagnosis",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="diagnostics.cie10group",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="diagnostics.cie10version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnóstico CIE-10",
                "verbose_name_plural": "Diagnósticos CIE-10",
                "db_table": "diagnostics_cie10_diagnoses",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="cie10chapter",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="diagnostics.cie10version",
            ),
        ),
        migrations.CreateModel(
            name="FavoriteDiagnosis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True, help_text="Especialidad médica", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diagnostics.cie10diagnosis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_diagnoses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnóstico Favorito",
                "verbose_name_plural": "Diagnósticos Favoritos",
                "db_table": "diagnostics_favorite_diagnoses",
                "ordering": ["order", "diagnosis__code"],
            },
        ),
        migrations.AddIndex(
            model_name="cie10diagnosis",
            index=models.Index(fields=["code"], name="diagnostics_code_13739a_idx"),
        ),
        migrations.AddIndex(
            model_name="cie10diagnosis",
            index=models.Index(
                fields=["version", "is_active"], name="diagnostics_version_518056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cie10diagnosis",
            index=models.Index(
                fields=["chapter"], name="diagnostics_chapter_e06af3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cie10diagnosis",
            unique_together={("version", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="cie10chapter",
            unique_together={("version", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="favoritediagnosis",
            unique_together={("company", "user", "diagnosis")},
        ),
    ]
