# Generated by Django 5.1.4 on 2025-10-14 19:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_usercompanypermission_can_access_billing_health_and_more"),
        ("diagnostics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisImportLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Nombre del Archivo"),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="diagnostics/imports/%Y/%m/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        default="csv",
                        help_text="csv, xlsx, xml",
                        max_length=20,
                        verbose_name="Tipo de Archivo",
                    ),
                ),
                (
                    "total_records",
                    models.IntegerField(default=0, verbose_name="Total de Registros"),
                ),
                (
                    "successful_imports",
                    models.IntegerField(
                        default=0, verbose_name="Importados Exitosamente"
                    ),
                ),
                (
                    "failed_imports",
                    models.IntegerField(default=0, verbose_name="Fallos"),
                ),
                (
                    "skipped_imports",
                    models.IntegerField(default=0, verbose_name="Omitidos"),
                ),
                (
                    "updated_records",
                    models.IntegerField(default=0, verbose_name="Actualizados"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                            ("partial", "Parcial"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(default=0, verbose_name="Progreso (%)"),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, verbose_name="Log de Errores"),
                ),
                (
                    "import_notes",
                    models.TextField(blank=True, verbose_name="Notas de Importación"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Resumen")),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado"
                    ),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duración (segundos)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Importación",
                "verbose_name_plural": "Logs de Importación",
                "db_table": "diagnostics_import_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="chronic_disease",
            field=models.BooleanField(
                default=False,
                help_text="Enfermedad crónica no transmisible",
                verbose_name="Enfermedad Crónica",
            ),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="death_type",
            field=models.CharField(
                choices=[
                    ("not_applicable", "No aplica"),
                    ("basic", "Causa básica"),
                    ("intermediate", "Causa intermedia"),
                    ("immediate", "Causa inmediata"),
                ],
                default="not_applicable",
                max_length=20,
                verbose_name="Tipo de Causa de Muerte",
            ),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="high_cost",
            field=models.BooleanField(
                default=False,
                help_text="Diagnóstico de enfermedad de alto costo (CAC)",
                verbose_name="Alto Costo",
            ),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="is_deprecated",
            field=models.BooleanField(default=False, verbose_name="Obsoleto"),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="last_used",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Último Uso"
            ),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="mandatory_notification",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si es enfermedad de notificación obligatoria al INS",
                verbose_name="Notificación Obligatoria (SIVIGILA)",
            ),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="rare_disease",
            field=models.BooleanField(
                default=False,
                help_text="Enfermedad huérfana según normativa colombiana",
                verbose_name="Enfermedad Huérfana/Rara",
            ),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="requires_authorization",
            field=models.BooleanField(
                default=False,
                help_text="Requiere autorización previa de la EPS",
                verbose_name="Requiere Autorización",
            ),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="synonyms",
            field=models.TextField(
                blank=True,
                help_text="Términos alternativos separados por comas",
                verbose_name="Sinónimos",
            ),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="use_in",
            field=models.CharField(
                choices=[
                    ("morbidity", "Morbilidad"),
                    ("mortality", "Mortalidad"),
                    ("both", "Ambos"),
                ],
                default="both",
                max_length=20,
                verbose_name="Uso en",
            ),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="valid_from",
            field=models.DateField(blank=True, null=True, verbose_name="Válido Desde"),
        ),
        migrations.AddField(
            model_name="cie10diagnosis",
            name="valid_until",
            field=models.DateField(blank=True, null=True, verbose_name="Válido Hasta"),
        ),
        migrations.AddField(
            model_name="favoritediagnosis",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notas Personales"),
        ),
        migrations.AlterField(
            model_name="cie10chapter",
            name="code",
            field=models.CharField(
                help_text="Código del capítulo (I, II, III, etc.)",
                max_length=10,
                verbose_name="Código del Capítulo",
            ),
        ),
        migrations.AlterField(
            model_name="cie10chapter",
            name="code_range_end",
            field=models.CharField(
                help_text="Ej: B99", max_length=10, verbose_name="Código Final"
            ),
        ),
        migrations.AlterField(
            model_name="cie10chapter",
            name="code_range_start",
            field=models.CharField(
                help_text="Ej: A00", max_length=10, verbose_name="Código Inicial"
            ),
        ),
        migrations.AlterField(
            model_name="cie10chapter",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Nombre del Capítulo"),
        ),
        migrations.AlterField(
            model_name="cie10chapter",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="applicable_gender",
            field=models.CharField(
                choices=[("A", "Ambos"), ("M", "Masculino"), ("F", "Femenino")],
                default="A",
                max_length=1,
                verbose_name="Sexo Aplicable",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diagnostics.cie10chapter",
                verbose_name="Capítulo",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Ej: A00, A00.1, Z99.9",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato CIE-10 inválido. Use: A00 o A00.1",
                        regex="^[A-Z][0-9]{2}(\\.[0-9X]{1,2})?$",
                    )
                ],
                verbose_name="Código CIE-10",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="excludes",
            field=models.TextField(
                blank=True,
                help_text="Condiciones excluidas de este código",
                verbose_name="Excluye",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diagnostics.cie10group",
                verbose_name="Grupo",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="includes",
            field=models.TextField(
                blank=True,
                help_text="Condiciones incluidas en este código",
                verbose_name="Incluye",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="is_category",
            field=models.BooleanField(
                default=False,
                help_text="Código de 3 caracteres",
                verbose_name="Es Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="is_subcategory",
            field=models.BooleanField(
                default=False,
                help_text="Código de 4+ caracteres",
                verbose_name="Es Subcategoría",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="level",
            field=models.IntegerField(
                default=0,
                help_text="3=categoría, 4=subcategoría, 5=sub-subcategoría",
                verbose_name="Nivel Jerárquico",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="max_age_days",
            field=models.IntegerField(
                blank=True,
                help_text="Edad máxima en días (dejar vacío si no aplica)",
                null=True,
                verbose_name="Edad Máxima (días)",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="min_age_days",
            field=models.IntegerField(
                blank=True,
                help_text="Edad mínima en días (365 días = 1 año)",
                null=True,
                verbose_name="Edad Mínima (días)",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="name",
            field=models.CharField(
                max_length=500, verbose_name="Descripción del Diagnóstico"
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Notas clínicas o aclaraciones",
                verbose_name="Notas Adicionales",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="diagnostics.cie10diagnosis",
                verbose_name="Diagnóstico Padre",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="search_vector",
            field=models.TextField(
                blank=True,
                help_text="Vector de búsqueda normalizado (auto-generado)",
                verbose_name="Vector de Búsqueda",
            ),
        ),
        migrations.AlterField(
            model_name="cie10diagnosis",
            name="use_count",
            field=models.IntegerField(
                default=0,
                help_text="Veces que se ha usado este diagnóstico",
                verbose_name="Contador de Uso",
            ),
        ),
        migrations.AlterField(
            model_name="cie10group",
            name="code_range_end",
            field=models.CharField(max_length=10, verbose_name="Código Final"),
        ),
        migrations.AlterField(
            model_name="cie10group",
            name="code_range_start",
            field=models.CharField(max_length=10, verbose_name="Código Inicial"),
        ),
        migrations.AlterField(
            model_name="cie10group",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Nombre del Grupo"),
        ),
        migrations.AlterField(
            model_name="cie10group",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AlterField(
            model_name="cie10version",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="cie10version",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="cie10version",
            name="is_current",
            field=models.BooleanField(
                default=False,
                help_text="Versión actual en uso",
                verbose_name="Versión Actual",
            ),
        ),
        migrations.AlterField(
            model_name="cie10version",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="cie10version",
            name="release_date",
            field=models.DateField(verbose_name="Fecha de Publicación"),
        ),
        migrations.AlterField(
            model_name="cie10version",
            name="version_code",
            field=models.CharField(
                help_text="Ej: CIE10-2023, CIE10-ES-2024",
                max_length=20,
                unique=True,
                verbose_name="Código de Versión",
            ),
        ),
        migrations.AlterField(
            model_name="favoritediagnosis",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_diagnoses",
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="favoritediagnosis",
            name="diagnosis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="diagnostics.cie10diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="favoritediagnosis",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AlterField(
            model_name="favoritediagnosis",
            name="specialty",
            field=models.CharField(
                blank=True,
                help_text="Ej: Cardiología, Pediatría, Medicina Interna",
                max_length=50,
                verbose_name="Especialidad Médica",
            ),
        ),
        migrations.AddIndex(
            model_name="cie10diagnosis",
            index=models.Index(
                fields=["mandatory_notification"], name="diagnostics_mandato_0f8345_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cie10diagnosis",
            index=models.Index(
                fields=["high_cost"], name="diagnostics_high_co_a38def_idx"
            ),
        ),
        migrations.AddField(
            model_name="diagnosisimportlog",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnosis_imports",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="diagnosisimportlog",
            name="imported_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnosis_imports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Importado Por",
            ),
        ),
        migrations.AddField(
            model_name="diagnosisimportlog",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imports",
                to="diagnostics.cie10version",
            ),
        ),
    ]
