# Generated by Django 4.2.21 on 2025-08-28 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('measure_type', models.CharField(choices=[('length', 'Longitud'), ('weight', 'Peso'), ('volume', 'Volumen'), ('area', 'Área'), ('time', 'Tiempo'), ('unit', 'Unidad'), ('other', 'Otro')], max_length=20)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='inventory.unitofmeasure')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units_of_measure', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'inventory_units_of_measure',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='core.company')),
                ('cost_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories_cost', to='accounting.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories_inventory', to='accounting.account')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.productcategory')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories_revenue', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Producto',
                'db_table': 'inventory_product_categories',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio'), ('kit', 'Kit'), ('raw_material', 'Materia Prima'), ('finished_good', 'Producto Terminado')], default='product', max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('internal_reference', models.CharField(blank=True, max_length=50)),
                ('supplier_reference', models.CharField(blank=True, max_length=50)),
                ('standard_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('last_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('list_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('costing_method', models.CharField(choices=[('average', 'Promedio Ponderado'), ('fifo', 'PEPS (Primero en Entrar, Primero en Salir)'), ('lifo', 'UEPS (Último en Entrar, Primero en Salir)'), ('standard', 'Costo Estándar')], default='average', max_length=20)),
                ('track_inventory', models.BooleanField(default=True)),
                ('track_lots', models.BooleanField(default=False)),
                ('track_serial_numbers', models.BooleanField(default=False)),
                ('track_expiration', models.BooleanField(default=False)),
                ('minimum_stock', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('maximum_stock', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('reorder_point', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_for_sale', models.BooleanField(default=True)),
                ('is_for_purchase', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.company')),
                ('cost_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_cost', to='accounting.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_inventory', to='accounting.account')),
                ('purchase_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_purchase', to='inventory.unitofmeasure')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_revenue', to='accounting.account')),
                ('sale_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_sale', to='inventory.unitofmeasure')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'inventory_products',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['company', 'name'], name='inventory_p_company_5a4316_idx'), models.Index(fields=['barcode'], name='inventory_p_barcode_2b7d27_idx'), models.Index(fields=['category'], name='inventory_p_categor_4a3921_idx'), models.Index(fields=['is_active'], name='inventory_p_is_acti_8fb186_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
