# Generated by Django 5.1.4 on 2025-09-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_warehouse_stockmovement_productstock"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productstock",
            new_name="inventory_p_product_77e458_idx",
            old_name="inventory_p_product_8b9c5d_idx",
        ),
        migrations.RenameIndex(
            model_name="productstock",
            new_name="inventory_p_quantit_a4ac43_idx",
            old_name="inventory_p_quantit_3a7f12_idx",
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="inventory_s_company_c993f8_idx",
            old_name="inventory_s_company_2fb06b_idx",
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="inventory_s_product_ba92d5_idx",
            old_name="inventory_s_product_95e2a4_idx",
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="inventory_s_movemen_373c04_idx",
            old_name="inventory_s_movemen_21f1a2_idx",
        ),
        migrations.RenameIndex(
            model_name="stockmovement",
            new_name="inventory_s_documen_d279b4_idx",
            old_name="inventory_s_documen_1e5b7c_idx",
        ),
    ]
