# Generated by Django 4.2.23 on 2025-08-28 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('balance_sheet', 'Balance General'), ('income_statement', 'Estado de Resultados'), ('cash_flow', 'Flujo de Efectivo'), ('trial_balance', 'Balance de Prueba'), ('general_ledger', 'Libro Mayor'), ('journal', 'Libro Diario'), ('aging_report', 'Cartera Vencida'), ('tax_report', 'Reporte de Impuestos'), ('payroll_report', 'Reporte de Nómina'), ('inventory_report', 'Reporte de Inventarios'), ('custom', 'Personalizado')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('template_config', models.JSONField(default=dict, help_text='Configuración JSON del template')),
                ('sql_query', models.TextField(blank=True, help_text='Query SQL personalizada')),
                ('page_format', models.CharField(default='A4', max_length=10)),
                ('orientation', models.CharField(choices=[('portrait', 'Vertical'), ('landscape', 'Horizontal')], default='portrait', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'db_table': 'reports_templates',
                'ordering': ['report_type', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('parameters', models.JSONField(default=dict, help_text='Parámetros específicos del reporte')),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/pdf/')),
                ('excel_file', models.FileField(blank=True, upload_to='reports/excel/')),
                ('status', models.CharField(choices=[('generating', 'Generando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='generating', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('file_size', models.IntegerField(default=0)),
                ('generation_time', models.FloatField(default=0, help_text='Tiempo de generación en segundos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'reports_generated',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='reports_gen_company_7ab82f_idx'), models.Index(fields=['template', 'period_start'], name='reports_gen_templat_d056ea_idx'), models.Index(fields=['status'], name='reports_gen_status_40c6c3_idx')],
            },
        ),
    ]
