# Generated by Django 5.1.4 on 2025-10-15 19:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_usercompanypermission_can_access_billing_health_and_more"),
        ("ophthalmology", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OphthalConsultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consultation_number", models.CharField(max_length=50, unique=True)),
                (
                    "consultation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "chief_complaint",
                    models.TextField(verbose_name="Motivo de consulta"),
                ),
                (
                    "ocular_history",
                    models.TextField(blank=True, verbose_name="Antecedentes oculares"),
                ),
                (
                    "family_ocular_history",
                    models.TextField(
                        blank=True, verbose_name="Antecedentes oculares familiares"
                    ),
                ),
                (
                    "systemic_history",
                    models.TextField(
                        blank=True, verbose_name="Antecedentes sistémicos"
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(blank=True, verbose_name="Medicamentos actuales"),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="Alergias")),
                ("symptoms", models.TextField(blank=True, verbose_name="Síntomas")),
                (
                    "uses_glasses",
                    models.BooleanField(default=False, verbose_name="Usa lentes"),
                ),
                (
                    "uses_contact_lenses",
                    models.BooleanField(
                        default=False, verbose_name="Usa lentes de contacto"
                    ),
                ),
                (
                    "diagnosis_right_eye",
                    models.TextField(blank=True, verbose_name="Diagnóstico OD"),
                ),
                (
                    "diagnosis_left_eye",
                    models.TextField(blank=True, verbose_name="Diagnóstico OI"),
                ),
                (
                    "diagnosis_both_eyes",
                    models.TextField(blank=True, verbose_name="Diagnóstico AO"),
                ),
                (
                    "treatment_plan",
                    models.TextField(blank=True, verbose_name="Plan de tratamiento"),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "next_appointment",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima cita"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "En Proceso"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ophthal_consultations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ophthalmologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ophthal_consultations_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ophthal_consultations",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta Oftalmológica",
                "verbose_name_plural": "Consultas Oftalmológicas",
                "db_table": "ophthalmology_consultation",
                "ordering": ["-consultation_date"],
            },
        ),
        migrations.CreateModel(
            name="LensPrescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prescription_number", models.CharField(max_length=50, unique=True)),
                (
                    "prescription_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "lens_type",
                    models.CharField(
                        choices=[
                            ("single_vision", "Visión Sencilla"),
                            ("bifocal", "Bifocal"),
                            ("progressive", "Progresivo"),
                            ("reading", "Solo Lectura"),
                            ("distance", "Solo Distancia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recommended_usage",
                    models.CharField(
                        choices=[
                            ("full_time", "Uso Permanente"),
                            ("distance", "Solo Distancia"),
                            ("near", "Solo Cerca"),
                            ("computer", "Computadora"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "od_sphere",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="OD Esfera"
                    ),
                ),
                (
                    "od_cylinder",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="OD Cilindro",
                    ),
                ),
                (
                    "od_axis",
                    models.IntegerField(blank=True, null=True, verbose_name="OD Eje"),
                ),
                (
                    "od_add",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="OD Adición",
                    ),
                ),
                (
                    "os_sphere",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="OI Esfera"
                    ),
                ),
                (
                    "os_cylinder",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="OI Cilindro",
                    ),
                ),
                (
                    "os_axis",
                    models.IntegerField(blank=True, null=True, verbose_name="OI Eje"),
                ),
                (
                    "os_add",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="OI Adición",
                    ),
                ),
                (
                    "pd_distance",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="mm",
                        max_digits=4,
                        verbose_name="DP Distancia",
                    ),
                ),
                (
                    "pd_near",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mm",
                        max_digits=4,
                        null=True,
                        verbose_name="DP Cerca",
                    ),
                ),
                (
                    "anti_reflective",
                    models.BooleanField(default=False, verbose_name="Antirreflejo"),
                ),
                (
                    "photochromic",
                    models.BooleanField(default=False, verbose_name="Fotocromático"),
                ),
                (
                    "blue_filter",
                    models.BooleanField(default=False, verbose_name="Filtro azul"),
                ),
                (
                    "polarized",
                    models.BooleanField(default=False, verbose_name="Polarizado"),
                ),
                (
                    "recommended_material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plastic", "Plástico (CR-39)"),
                            ("polycarbonate", "Policarbonato"),
                            ("high_index", "Alto Índice"),
                            ("trivex", "Trivex"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Válida hasta"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ophthalmologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lens_prescriptions_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lens_prescriptions",
                        to="patients.patient",
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lens_prescriptions",
                        to="ophthalmology.ophthalconsultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescripción de Lentes",
                "verbose_name_plural": "Prescripciones de Lentes",
                "db_table": "ophthalmology_lens_prescription",
                "ordering": ["-prescription_date"],
            },
        ),
        migrations.CreateModel(
            name="IntraocularPressure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "od_pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mmHg",
                        max_digits=4,
                        null=True,
                        verbose_name="PIO OD",
                    ),
                ),
                (
                    "os_pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mmHg",
                        max_digits=4,
                        null=True,
                        verbose_name="PIO OI",
                    ),
                ),
                (
                    "measurement_method",
                    models.CharField(
                        choices=[
                            ("goldmann", "Tonometría de Goldmann (Aplanación)"),
                            ("pneumatic", "Tonometría Neumática"),
                            ("perkins", "Tonometría de Perkins"),
                            ("icare", "Tonometría de Rebote (iCare)"),
                            ("tono_pen", "Tono-Pen"),
                        ],
                        default="goldmann",
                        max_length=20,
                    ),
                ),
                ("measurement_time", models.TimeField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pressures_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intraocular_pressure",
                        to="ophthalmology.ophthalconsultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presión Intraocular",
                "verbose_name_plural": "Presiones Intraoculares",
                "db_table": "ophthalmology_intraocular_pressure",
            },
        ),
        migrations.CreateModel(
            name="FundusExam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "examination_method",
                    models.CharField(
                        choices=[
                            ("direct", "Oftalmoscopía Directa"),
                            ("indirect", "Oftalmoscopía Indirecta"),
                            ("slit_lamp", "Biomicroscopía con Lente"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "pupil_dilation",
                    models.BooleanField(
                        default=False, verbose_name="Dilatación pupilar"
                    ),
                ),
                (
                    "dilating_agent",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Midriático usado"
                    ),
                ),
                (
                    "od_media",
                    models.TextField(
                        blank=True,
                        help_text="Claridad de medios",
                        verbose_name="OD Medios",
                    ),
                ),
                (
                    "od_optic_disc",
                    models.TextField(blank=True, verbose_name="OD Disco Óptico"),
                ),
                (
                    "od_cup_disc_ratio",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 0.3",
                        max_length=10,
                        verbose_name="OD Relación E/D",
                    ),
                ),
                ("od_vessels", models.TextField(blank=True, verbose_name="OD Vasos")),
                ("od_macula", models.TextField(blank=True, verbose_name="OD Mácula")),
                (
                    "od_periphery",
                    models.TextField(blank=True, verbose_name="OD Periferia"),
                ),
                ("os_media", models.TextField(blank=True, verbose_name="OI Medios")),
                (
                    "os_optic_disc",
                    models.TextField(blank=True, verbose_name="OI Disco Óptico"),
                ),
                (
                    "os_cup_disc_ratio",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="OI Relación E/D"
                    ),
                ),
                ("os_vessels", models.TextField(blank=True, verbose_name="OI Vasos")),
                ("os_macula", models.TextField(blank=True, verbose_name="OI Mácula")),
                (
                    "os_periphery",
                    models.TextField(blank=True, verbose_name="OI Periferia"),
                ),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fundus_exams_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundus_exam",
                        to="ophthalmology.ophthalconsultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fondo de Ojo",
                "verbose_name_plural": "Fondos de Ojo",
                "db_table": "ophthalmology_fundus_exam",
            },
        ),
        migrations.CreateModel(
            name="Biomicroscopy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "od_lids_lashes",
                    models.TextField(blank=True, verbose_name="OD Párpados y Pestañas"),
                ),
                (
                    "od_conjunctiva",
                    models.TextField(blank=True, verbose_name="OD Conjuntiva"),
                ),
                ("od_cornea", models.TextField(blank=True, verbose_name="OD Córnea")),
                (
                    "od_anterior_chamber",
                    models.TextField(blank=True, verbose_name="OD Cámara Anterior"),
                ),
                ("od_iris", models.TextField(blank=True, verbose_name="OD Iris")),
                ("od_lens", models.TextField(blank=True, verbose_name="OD Cristalino")),
                (
                    "os_lids_lashes",
                    models.TextField(blank=True, verbose_name="OI Párpados y Pestañas"),
                ),
                (
                    "os_conjunctiva",
                    models.TextField(blank=True, verbose_name="OI Conjuntiva"),
                ),
                ("os_cornea", models.TextField(blank=True, verbose_name="OI Córnea")),
                (
                    "os_anterior_chamber",
                    models.TextField(blank=True, verbose_name="OI Cámara Anterior"),
                ),
                ("os_iris", models.TextField(blank=True, verbose_name="OI Iris")),
                ("os_lens", models.TextField(blank=True, verbose_name="OI Cristalino")),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biomicroscopies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biomicroscopy",
                        to="ophthalmology.ophthalconsultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biomicroscopía",
                "verbose_name_plural": "Biomicroscopías",
                "db_table": "ophthalmology_biomicroscopy",
            },
        ),
        migrations.CreateModel(
            name="Refraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "od_sphere",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dioptrías",
                        max_digits=5,
                        null=True,
                        verbose_name="OD Esfera",
                    ),
                ),
                (
                    "od_cylinder",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="OD Cilindro",
                    ),
                ),
                (
                    "od_axis",
                    models.IntegerField(
                        blank=True,
                        help_text="0-180 grados",
                        null=True,
                        verbose_name="OD Eje",
                    ),
                ),
                (
                    "od_add",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Para presbicia",
                        max_digits=4,
                        null=True,
                        verbose_name="OD Adición",
                    ),
                ),
                (
                    "od_prism",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="OD Prisma"
                    ),
                ),
                (
                    "os_sphere",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="OI Esfera",
                    ),
                ),
                (
                    "os_cylinder",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="OI Cilindro",
                    ),
                ),
                (
                    "os_axis",
                    models.IntegerField(blank=True, null=True, verbose_name="OI Eje"),
                ),
                (
                    "os_add",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="OI Adición",
                    ),
                ),
                (
                    "os_prism",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="OI Prisma"
                    ),
                ),
                (
                    "pd_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mm",
                        max_digits=4,
                        null=True,
                        verbose_name="DP Distancia",
                    ),
                ),
                (
                    "pd_near",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="mm",
                        max_digits=4,
                        null=True,
                        verbose_name="DP Cerca",
                    ),
                ),
                (
                    "refraction_type",
                    models.CharField(
                        choices=[
                            ("subjective", "Subjetiva"),
                            ("objective", "Objetiva (Retinoscopia/Autorefractor)"),
                            ("cycloplegic", "Ciclopléjica"),
                        ],
                        default="subjective",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refraction",
                        to="ophthalmology.ophthalconsultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refractions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Refracción",
                "verbose_name_plural": "Refracciones",
                "db_table": "ophthalmology_refraction",
            },
        ),
        migrations.CreateModel(
            name="VisualAcuity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "od_distance_sc",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 20/20, 20/40",
                        max_length=20,
                        verbose_name="OD Distancia SC",
                    ),
                ),
                (
                    "od_near_sc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="OD Cerca SC"
                    ),
                ),
                (
                    "od_distance_cc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="OD Distancia CC"
                    ),
                ),
                (
                    "od_near_cc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="OD Cerca CC"
                    ),
                ),
                (
                    "os_distance_sc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="OI Distancia SC"
                    ),
                ),
                (
                    "os_near_sc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="OI Cerca SC"
                    ),
                ),
                (
                    "os_distance_cc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="OI Distancia CC"
                    ),
                ),
                (
                    "os_near_cc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="OI Cerca CC"
                    ),
                ),
                (
                    "ou_distance_sc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="AO Distancia SC"
                    ),
                ),
                (
                    "ou_near_sc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="AO Cerca SC"
                    ),
                ),
                (
                    "ou_distance_cc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="AO Distancia CC"
                    ),
                ),
                (
                    "ou_near_cc",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="AO Cerca CC"
                    ),
                ),
                (
                    "od_pinhole",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="OD Estenopeico"
                    ),
                ),
                (
                    "os_pinhole",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="OI Estenopeico"
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_acuity",
                        to="ophthalmology.ophthalconsultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visual_acuities_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agudeza Visual",
                "verbose_name_plural": "Agudezas Visuales",
                "db_table": "ophthalmology_visual_acuity",
            },
        ),
        migrations.DeleteModel(
            name="OphthalmologyModule",
        ),
    ]
