# Generated by Django 4.2.21 on 2025-08-28 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('useful_life_years', models.IntegerField(default=5, help_text='Vida útil en años')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Línea Recta'), ('declining_balance', 'Saldos Decrecientes'), ('sum_of_years', 'Suma de Años Dígitos')], default='straight_line', max_length=20)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_asset', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_depreciation', to='accounting.account')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_expense', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Categoría de Activo',
                'verbose_name_plural': 'Categorías de Activos',
                'db_table': 'fixed_assets_categories',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('acquisition_date', models.DateField()),
                ('start_depreciation_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('useful_life_years', models.IntegerField()),
                ('useful_life_months', models.IntegerField(default=0)),
                ('depreciation_method', models.CharField(default='straight_line', max_length=20)),
                ('depreciable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_book_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('disposed', 'Dado de Baja'), ('sold', 'Vendido'), ('transferred', 'Transferido')], default='active', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fixed_assets.assetcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='core.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'db_table': 'fixed_assets',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['company', 'category'], name='fixed_asset_company_559939_idx'), models.Index(fields=['status'], name='fixed_asset_status_a2feec_idx'), models.Index(fields=['cost_center'], name='fixed_asset_cost_ce_2aa156_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
