# Generated by Django 5.1.4 on 2025-09-11 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0002_remove_journalentry_accounting__period__7c4b66_idx_and_more",
        ),
        ("core", "0002_user_default_company"),
        ("fixed_assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transfer_date", models.DateField()),
                ("from_location", models.CharField(blank=True, max_length=200)),
                ("to_location", models.CharField(blank=True, max_length=200)),
                ("reason", models.TextField()),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("approved", "Aprobado"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="fixed_assets.fixedasset",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_transfers",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_transfers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_transfers_from",
                        to="accounting.costcenter",
                    ),
                ),
                (
                    "from_responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_transfers_from_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_transfers_to",
                        to="accounting.costcenter",
                    ),
                ),
                (
                    "to_responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_transfers_to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferencia de Activo",
                "verbose_name_plural": "Transferencias de Activos",
                "db_table": "fixed_assets_transfers",
                "ordering": ["-transfer_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "transfer_date"],
                        name="fixed_asset_company_08ba25_idx",
                    ),
                    models.Index(
                        fields=["asset", "status"],
                        name="fixed_asset_asset_i_a9d698_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DepreciationEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_year", models.IntegerField()),
                ("period_month", models.IntegerField()),
                ("depreciation_date", models.DateField()),
                (
                    "depreciation_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "accumulated_before",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "accumulated_after",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("method_used", models.CharField(max_length=20)),
                ("voucher_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("posted", "Contabilizado"),
                            ("reversed", "Reversado"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_entries",
                        to="fixed_assets.fixedasset",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_entries",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depreciation_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.currency"
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depreciation_entries",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Depreciación",
                "verbose_name_plural": "Registros de Depreciación",
                "db_table": "fixed_assets_depreciation_entries",
                "ordering": ["-period_year", "-period_month", "asset__code"],
                "indexes": [
                    models.Index(
                        fields=["company", "period_year", "period_month"],
                        name="fixed_asset_company_4d1ad9_idx",
                    ),
                    models.Index(
                        fields=["asset", "depreciation_date"],
                        name="fixed_asset_asset_i_4dcbc4_idx",
                    ),
                    models.Index(
                        fields=["status"], name="fixed_asset_status_2c9b2f_idx"
                    ),
                ],
                "unique_together": {
                    ("company", "asset", "period_year", "period_month")
                },
            },
        ),
    ]
