# Generated by Django 5.1.4 on 2025-10-15 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_usercompanypermission_can_access_billing_health_and_more"),
        ("patients", "0001_initial"),
        ("telemedicine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeCareVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visit_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Visita"
                    ),
                ),
                (
                    "accompanying_staff",
                    models.TextField(
                        blank=True,
                        help_text="Auxiliares, enfermeras, etc.",
                        verbose_name="Personal Acompañante",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("medical_consultation", "Consulta Médica"),
                            ("nursing_care", "Cuidado de Enfermería"),
                            ("therapy", "Terapia"),
                            ("follow_up", "Seguimiento"),
                            ("emergency", "Emergencia"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Visita",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(verbose_name="Fecha y Hora Programada"),
                ),
                (
                    "actual_arrival_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Llegada"
                    ),
                ),
                (
                    "actual_departure_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Salida"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duración (minutos)"
                    ),
                ),
                ("address", models.TextField(verbose_name="Dirección Completa")),
                ("city", models.CharField(max_length=100, verbose_name="Ciudad")),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="Barrio"),
                ),
                (
                    "landmark_reference",
                    models.TextField(
                        blank=True, verbose_name="Referencias de Ubicación"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono de Contacto"
                    ),
                ),
                ("visit_reason", models.TextField(verbose_name="Motivo de la Visita")),
                (
                    "patient_condition_on_arrival",
                    models.TextField(
                        blank=True, verbose_name="Estado del Paciente al Llegar"
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Presión Arterial"
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Frecuencia Cardíaca"
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Frecuencia Respiratoria"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Temperatura",
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Saturación de Oxígeno (%)"
                    ),
                ),
                (
                    "procedures_performed",
                    models.TextField(
                        blank=True, verbose_name="Procedimientos Realizados"
                    ),
                ),
                (
                    "medications_administered",
                    models.TextField(
                        blank=True, verbose_name="Medicamentos Administrados"
                    ),
                ),
                (
                    "medical_supplies_used",
                    models.TextField(
                        blank=True, verbose_name="Insumos Médicos Utilizados"
                    ),
                ),
                (
                    "clinical_assessment",
                    models.TextField(verbose_name="Evaluación Clínica"),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Diagnóstico")),
                (
                    "treatment_provided",
                    models.TextField(
                        blank=True, verbose_name="Tratamiento Proporcionado"
                    ),
                ),
                (
                    "instructions_to_patient",
                    models.TextField(
                        blank=True, verbose_name="Instrucciones al Paciente/Familia"
                    ),
                ),
                (
                    "instructions_to_caregiver",
                    models.TextField(
                        blank=True, verbose_name="Instrucciones al Cuidador"
                    ),
                ),
                (
                    "next_visit_required",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Próxima Visita"
                    ),
                ),
                (
                    "next_visit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Próxima Visita"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("in_route", "En Ruta"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "patient_satisfaction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excelente"),
                            ("good", "Buena"),
                            ("fair", "Regular"),
                            ("poor", "Mala"),
                        ],
                        max_length=20,
                        verbose_name="Satisfacción del Paciente",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "complications",
                    models.TextField(
                        blank=True, verbose_name="Complicaciones o Incidentes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_care_visits",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_care_visits_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "healthcare_professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_care_visits_as_professional",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profesional de Salud",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_care_visits",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atención Domiciliaria",
                "verbose_name_plural": "Atenciones Domiciliarias",
                "db_table": "telemedicine_home_care_visit",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Documento"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("prescription", "Receta Médica"),
                            ("medical_certificate", "Certificado Médico"),
                            ("sick_leave", "Incapacidad"),
                            ("lab_order", "Orden de Laboratorio"),
                            ("imaging_order", "Orden de Imagen"),
                            ("referral", "Remisión"),
                            ("medical_report", "Informe Médico"),
                            ("consent", "Consentimiento Informado"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "document_title",
                    models.CharField(
                        max_length=200, verbose_name="Título del Documento"
                    ),
                ),
                (
                    "document_content",
                    models.TextField(verbose_name="Contenido del Documento"),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Diagnóstico")),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("issue_date", models.DateField(verbose_name="Fecha de Emisión")),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Válido Hasta"
                    ),
                ),
                (
                    "is_digitally_signed",
                    models.BooleanField(
                        default=False, verbose_name="Firmado Digitalmente"
                    ),
                ),
                (
                    "signature_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Firma"
                    ),
                ),
                (
                    "digital_signature_hash",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Hash de Firma Digital"
                    ),
                ),
                (
                    "pdf_file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Ruta del Archivo PDF"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemedicine_documents",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telemedicine_documents_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "home_care_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="telemedicine.homecarevisit",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telemedicine_documents",
                        to="patients.patient",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Firmado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Médico",
                "verbose_name_plural": "Documentos Médicos",
                "db_table": "telemedicine_document",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="DigitalSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signature_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora de Firma"
                    ),
                ),
                (
                    "signature_hash",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Hash de Firma"
                    ),
                ),
                (
                    "signature_method",
                    models.CharField(
                        default="SHA256", max_length=50, verbose_name="Método de Firma"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Dirección IP"),
                ),
                (
                    "device_info",
                    models.TextField(
                        blank=True, verbose_name="Información del Dispositivo"
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="Firma Válida"),
                ),
                (
                    "verification_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Verificación"
                    ),
                ),
                (
                    "certificate_serial",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Serial del Certificado",
                    ),
                ),
                (
                    "certificate_issuer",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Emisor del Certificado",
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_signatures",
                        to="core.company",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_signatures_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to="telemedicine.medicaldocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firma Digital",
                "verbose_name_plural": "Firmas Digitales",
                "db_table": "telemedicine_digital_signature",
                "ordering": ["-signature_date"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicineAppointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "appointment_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Cita"
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("virtual", "Consulta Virtual"),
                            ("home_care", "Atención Domiciliaria"),
                            ("phone", "Consulta Telefónica"),
                            ("chat", "Consulta por Chat"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Consulta",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(verbose_name="Fecha y Hora Programada"),
                ),
                (
                    "actual_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Inicio Real"
                    ),
                ),
                (
                    "actual_end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Fin Real"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=30, verbose_name="Duración (minutos)"),
                ),
                ("reason", models.TextField(verbose_name="Motivo de Consulta")),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Especialidad"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Rutina"),
                            ("urgent", "Urgente"),
                            ("emergency", "Emergencia"),
                        ],
                        default="routine",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Enlace de Reunión"
                    ),
                ),
                (
                    "meeting_platform",
                    models.CharField(
                        blank=True,
                        help_text="Zoom, Teams, Google Meet, etc.",
                        max_length=50,
                        verbose_name="Plataforma",
                    ),
                ),
                (
                    "meeting_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID de Reunión"
                    ),
                ),
                (
                    "meeting_password",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contraseña de Reunión"
                    ),
                ),
                (
                    "home_address",
                    models.TextField(blank=True, verbose_name="Dirección Domiciliaria"),
                ),
                (
                    "home_city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
                ),
                (
                    "home_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono de Contacto"
                    ),
                ),
                (
                    "special_instructions",
                    models.TextField(
                        blank=True, verbose_name="Instrucciones Especiales"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("confirmed", "Confirmada"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("no_show", "No Asistió"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "confirmation_sent",
                    models.BooleanField(
                        default=False, verbose_name="Confirmación Enviada"
                    ),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, verbose_name="Recordatorio Enviado"
                    ),
                ),
                (
                    "pre_consultation_notes",
                    models.TextField(blank=True, verbose_name="Notas Pre-Consulta"),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Razón de Cancelación"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemedicine_appointments",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telemedicine_appointments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telemedicine_appointments_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Médico",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telemedicine_appointments",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita de Telemedicina",
                "verbose_name_plural": "Citas de Telemedicina",
                "db_table": "telemedicine_appointment",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.AddField(
            model_name="homecarevisit",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="home_care_visit",
                to="telemedicine.telemedicineappointment",
                verbose_name="Cita Asociada",
            ),
        ),
        migrations.CreateModel(
            name="TelemedicineStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Período Desde")),
                ("period_end", models.DateField(verbose_name="Período Hasta")),
                (
                    "total_appointments",
                    models.IntegerField(default=0, verbose_name="Total de Citas"),
                ),
                (
                    "completed_appointments",
                    models.IntegerField(default=0, verbose_name="Citas Completadas"),
                ),
                (
                    "cancelled_appointments",
                    models.IntegerField(default=0, verbose_name="Citas Canceladas"),
                ),
                (
                    "virtual_consultations_count",
                    models.IntegerField(default=0, verbose_name="Consultas Virtuales"),
                ),
                (
                    "home_care_visits_count",
                    models.IntegerField(
                        default=0, verbose_name="Atenciones Domiciliarias"
                    ),
                ),
                (
                    "documents_generated",
                    models.IntegerField(default=0, verbose_name="Documentos Generados"),
                ),
                (
                    "digital_signatures_count",
                    models.IntegerField(default=0, verbose_name="Firmas Digitales"),
                ),
                (
                    "average_consultation_duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Duración Promedio (minutos)",
                    ),
                ),
                (
                    "patient_satisfaction_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        verbose_name="Satisfacción Promedio",
                    ),
                ),
                (
                    "statistics_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Datos Estadísticos Adicionales",
                    ),
                ),
                (
                    "generated_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemedicine_statistics",
                        to="core.company",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telemedicine_stats_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadísticas de Telemedicina",
                "verbose_name_plural": "Estadísticas de Telemedicina",
                "db_table": "telemedicine_statistics",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="VirtualConsultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consultation_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Número de Consulta"
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("video", "Videollamada"),
                            ("phone", "Telefónica"),
                            ("chat", "Chat"),
                            ("mixed", "Mixta"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                (
                    "consultation_date",
                    models.DateTimeField(verbose_name="Fecha de Consulta"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(verbose_name="Duración (minutos)"),
                ),
                (
                    "chief_complaint",
                    models.TextField(verbose_name="Motivo de Consulta"),
                ),
                ("symptoms", models.TextField(verbose_name="Síntomas Presentados")),
                (
                    "symptoms_duration",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Duración de Síntomas"
                    ),
                ),
                (
                    "remote_examination",
                    models.TextField(
                        blank=True,
                        help_text="Inspección visual, evaluación de síntomas observables",
                        verbose_name="Examen Remoto",
                    ),
                ),
                (
                    "vital_signs_reported",
                    models.TextField(
                        blank=True,
                        verbose_name="Signos Vitales Reportados por Paciente",
                    ),
                ),
                ("diagnosis", models.TextField(verbose_name="Diagnóstico")),
                (
                    "treatment_plan",
                    models.TextField(verbose_name="Plan de Tratamiento"),
                ),
                (
                    "medications_prescribed",
                    models.TextField(
                        blank=True, verbose_name="Medicamentos Prescritos"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Recomendaciones"),
                ),
                (
                    "requires_in_person_visit",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Visita Presencial"
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, verbose_name="Requiere Seguimiento"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Seguimiento"
                    ),
                ),
                (
                    "lab_tests_ordered",
                    models.TextField(
                        blank=True, verbose_name="Laboratorios Solicitados"
                    ),
                ),
                (
                    "imaging_studies_ordered",
                    models.TextField(
                        blank=True, verbose_name="Estudios de Imagen Solicitados"
                    ),
                ),
                (
                    "sick_leave_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Días de Incapacidad"
                    ),
                ),
                (
                    "medical_certificate_issued",
                    models.BooleanField(
                        default=False, verbose_name="Certificado Médico Emitido"
                    ),
                ),
                (
                    "connection_quality",
                    models.CharField(
                        choices=[
                            ("excellent", "Excelente"),
                            ("good", "Buena"),
                            ("fair", "Regular"),
                            ("poor", "Mala"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="Calidad de Conexión",
                    ),
                ),
                (
                    "technical_issues",
                    models.TextField(blank=True, verbose_name="Problemas Técnicos"),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, verbose_name="Observaciones Generales"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_consultation",
                        to="telemedicine.telemedicineappointment",
                        verbose_name="Cita Asociada",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_consultations",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_consultations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_consultations_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virtual_consultations",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta Virtual",
                "verbose_name_plural": "Consultas Virtuales",
                "db_table": "telemedicine_virtual_consultation",
                "ordering": ["-consultation_date"],
            },
        ),
        migrations.AddField(
            model_name="medicaldocument",
            name="virtual_consultation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="telemedicine.virtualconsultation",
            ),
        ),
        migrations.DeleteModel(
            name="TelemedicineModule",
        ),
        migrations.AddIndex(
            model_name="telemedicineappointment",
            index=models.Index(
                fields=["company", "status"], name="telemedicin_company_81eae8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="telemedicineappointment",
            index=models.Index(
                fields=["patient", "scheduled_date"],
                name="telemedicin_patient_06d5cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="telemedicineappointment",
            index=models.Index(
                fields=["doctor", "scheduled_date"],
                name="telemedicin_doctor__e2ac92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="homecarevisit",
            index=models.Index(
                fields=["company", "status"], name="telemedicin_company_75ceae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homecarevisit",
            index=models.Index(
                fields=["patient", "scheduled_date"],
                name="telemedicin_patient_47fa77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="virtualconsultation",
            index=models.Index(
                fields=["company", "consultation_date"],
                name="telemedicin_company_b91289_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="virtualconsultation",
            index=models.Index(
                fields=["patient", "consultation_date"],
                name="telemedicin_patient_51d804_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocument",
            index=models.Index(
                fields=["company", "document_type"],
                name="telemedicin_company_6ab5b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocument",
            index=models.Index(
                fields=["patient", "issue_date"], name="telemedicin_patient_e6094a_idx"
            ),
        ),
    ]
