# Generated by Django 5.1.4 on 2025-09-11 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "requires_specialties",
                    models.BooleanField(
                        default=False, help_text="Requiere especialidades profesionales"
                    ),
                ),
                (
                    "has_patients",
                    models.BooleanField(
                        default=False, help_text="Maneja pacientes/clientes especiales"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoría de Empresa",
                "verbose_name_plural": "Categorías de Empresa",
                "db_table": "payroll_company_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HealthcareRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medico", "Médicos"),
                            ("enfermeria", "Enfermería"),
                            ("tecnico", "Técnicos Especializados"),
                            ("administrativo", "Personal Administrativo"),
                            ("servicios", "Servicios Generales"),
                            ("apoyo", "Personal de Apoyo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("requires_medical_license", models.BooleanField(default=False)),
                ("requires_specialty", models.BooleanField(default=False)),
                (
                    "is_clinical_role",
                    models.BooleanField(
                        default=False,
                        help_text="Rol clínico con contacto directo con pacientes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Rol de Salud",
                "verbose_name_plural": "Roles de Salud",
                "db_table": "payroll_healthcare_roles",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="MedicalSpecialty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "specialty_type",
                    models.CharField(
                        choices=[
                            ("medica", "Especialidad Médica"),
                            ("enfermeria", "Especialidad de Enfermería"),
                            ("tecnica", "Especialidad Técnica"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clinica", "Especialidades Clínicas"),
                            ("quirurgica", "Especialidades Quirúrgicas"),
                            ("materno_infantil", "Materno-Infantiles"),
                            ("apoyo_diagnostico", "Apoyo Diagnóstico"),
                            ("cuidados_criticos", "Cuidados Críticos"),
                            ("salud_mental", "Salud Mental"),
                            ("medicina_preventiva", "Medicina Preventiva"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("requires_subspecialty", models.BooleanField(default=False)),
                (
                    "years_of_training",
                    models.IntegerField(
                        default=0, help_text="Años de formación especializada"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Especialidad Médica",
                "verbose_name_plural": "Especialidades Médicas",
                "db_table": "payroll_medical_specialties",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="NursingSpecialty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("certification_required", models.BooleanField(default=False)),
                (
                    "continuing_education_hours",
                    models.IntegerField(
                        default=0,
                        help_text="Horas de educación continua requeridas anualmente",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Especialidad de Enfermería",
                "verbose_name_plural": "Especialidades de Enfermería",
                "db_table": "payroll_nursing_specialties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeHealthcareProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subspecialty",
                    models.CharField(
                        blank=True,
                        help_text="Subespecialidad adicional",
                        max_length=200,
                    ),
                ),
                (
                    "medical_license_number",
                    models.CharField(
                        blank=True, help_text="Número de registro médico", max_length=50
                    ),
                ),
                ("medical_license_expiry", models.DateField(blank=True, null=True)),
                (
                    "nursing_license_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de tarjeta profesional de enfermería",
                        max_length=50,
                    ),
                ),
                ("nursing_license_expiry", models.DateField(blank=True, null=True)),
                (
                    "certifications",
                    models.JSONField(
                        default=list, help_text="Lista de certificaciones adicionales"
                    ),
                ),
                (
                    "assigned_department",
                    models.CharField(
                        blank=True,
                        help_text="Departamento específico asignado",
                        max_length=100,
                    ),
                ),
                (
                    "shift_schedule",
                    models.CharField(
                        blank=True, help_text="Horario de turno", max_length=50
                    ),
                ),
                (
                    "years_experience",
                    models.IntegerField(
                        default=0, help_text="Años de experiencia en el área"
                    ),
                ),
                ("license_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="healthcare_profile",
                        to="payroll.employee",
                    ),
                ),
                (
                    "healthcare_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.healthcarerole",
                    ),
                ),
                (
                    "medical_specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.medicalspecialty",
                    ),
                ),
                (
                    "nursing_specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.nursingspecialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Salud del Empleado",
                "verbose_name_plural": "Perfiles de Salud de Empleados",
                "db_table": "payroll_employee_healthcare_profiles",
            },
        ),
    ]
