# Generated by Django 5.1.4 on 2025-09-11 20:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_companycategory_healthcarerole_medicalspecialty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaboratorySpecialty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "specialty_area",
                    models.CharField(
                        choices=[
                            ("hematology", "Hematología"),
                            ("chemistry", "Química Clínica"),
                            ("microbiology", "Microbiología"),
                            ("pathology", "Patología"),
                            ("molecular", "Diagnóstico Molecular"),
                            ("blood_bank", "Banco de Sangre"),
                            ("immunology", "Inmunología"),
                            ("cytology", "Citología"),
                            ("toxicology", "Toxicología"),
                            ("parasitology", "Parasitología"),
                            ("mycology", "Micología"),
                            ("virology", "Virología"),
                            ("gynecology_lab", "Laboratorio de Ginecología"),
                            ("emergency_lab", "Laboratorio de Urgencias"),
                            ("quality_control", "Control de Calidad"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("certification_required", models.BooleanField(default=False)),
                ("requires_special_training", models.BooleanField(default=False)),
                (
                    "training_hours_required",
                    models.IntegerField(
                        default=0, help_text="Horas de capacitación requeridas"
                    ),
                ),
                (
                    "associated_equipment",
                    models.JSONField(
                        default=list, help_text="Lista de equipos específicos"
                    ),
                ),
                (
                    "required_certifications",
                    models.JSONField(
                        default=list, help_text="Certificaciones requeridas"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Especialidad de Laboratorio",
                "verbose_name_plural": "Especialidades de Laboratorio",
                "db_table": "payroll_laboratory_specialties",
                "ordering": ["specialty_area", "name"],
            },
        ),
        migrations.AlterField(
            model_name="healthcarerole",
            name="category",
            field=models.CharField(
                choices=[
                    ("medico", "Médicos"),
                    ("enfermeria", "Enfermería"),
                    ("laboratorio", "Personal de Laboratorio"),
                    ("tecnico", "Técnicos Especializados"),
                    ("administrativo", "Personal Administrativo"),
                    ("servicios", "Servicios Generales"),
                    ("apoyo", "Personal de Apoyo"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="medicalspecialty",
            name="category",
            field=models.CharField(
                choices=[
                    ("clinica", "Especialidades Clínicas"),
                    ("quirurgica", "Especialidades Quirúrgicas"),
                    ("materno_infantil", "Materno-Infantiles"),
                    ("apoyo_diagnostico", "Apoyo Diagnóstico"),
                    ("laboratorio", "Especialidades de Laboratorio"),
                    ("cuidados_criticos", "Cuidados Críticos"),
                    ("salud_mental", "Salud Mental"),
                    ("medicina_preventiva", "Medicina Preventiva"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employeehealthcareprofile",
            name="laboratory_specialty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="payroll.laboratoryspecialty",
            ),
        ),
    ]
