# Generated by Django 5.1.4 on 2025-10-15 19:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_usercompanypermission_can_access_billing_health_and_more"),
        ("patients", "0001_initial"),
        ("psychology", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PsychologicalConsultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consultation_number", models.CharField(max_length=50, unique=True)),
                (
                    "consultation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "chief_complaint",
                    models.TextField(verbose_name="Motivo de consulta"),
                ),
                (
                    "referred_by",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Referido por"
                    ),
                ),
                (
                    "personal_history",
                    models.TextField(blank=True, verbose_name="Historia personal"),
                ),
                (
                    "family_history",
                    models.TextField(blank=True, verbose_name="Historia familiar"),
                ),
                (
                    "medical_history",
                    models.TextField(blank=True, verbose_name="Historia médica"),
                ),
                (
                    "psychiatric_history",
                    models.TextField(
                        blank=True, verbose_name="Antecedentes psiquiátricos"
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(blank=True, verbose_name="Medicación actual"),
                ),
                (
                    "substance_use",
                    models.TextField(blank=True, verbose_name="Uso de sustancias"),
                ),
                (
                    "appearance",
                    models.TextField(blank=True, verbose_name="Apariencia general"),
                ),
                ("behavior", models.TextField(blank=True, verbose_name="Conducta")),
                ("speech", models.TextField(blank=True, verbose_name="Lenguaje")),
                (
                    "mood",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Estado de ánimo"
                    ),
                ),
                (
                    "affect",
                    models.CharField(blank=True, max_length=100, verbose_name="Afecto"),
                ),
                (
                    "thought_process",
                    models.TextField(blank=True, verbose_name="Proceso de pensamiento"),
                ),
                (
                    "thought_content",
                    models.TextField(
                        blank=True, verbose_name="Contenido del pensamiento"
                    ),
                ),
                ("perception", models.TextField(blank=True, verbose_name="Percepción")),
                ("cognition", models.TextField(blank=True, verbose_name="Cognición")),
                (
                    "insight",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Insight"
                    ),
                ),
                (
                    "judgment",
                    models.CharField(blank=True, max_length=100, verbose_name="Juicio"),
                ),
                (
                    "suicide_risk",
                    models.CharField(
                        choices=[
                            ("none", "Sin riesgo"),
                            ("low", "Bajo"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Riesgo suicida",
                    ),
                ),
                (
                    "homicide_risk",
                    models.CharField(
                        choices=[
                            ("none", "Sin riesgo"),
                            ("low", "Bajo"),
                            ("medium", "Medio"),
                            ("high", "Alto"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Riesgo homicida",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(verbose_name="Diagnóstico/Impresión clínica"),
                ),
                (
                    "dsm_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Código DSM-5"
                    ),
                ),
                (
                    "treatment_recommendations",
                    models.TextField(verbose_name="Recomendaciones de tratamiento"),
                ),
                (
                    "therapy_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Tipo de terapia recomendada",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Frecuencia recomendada",
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psych_consultations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychological_consultations",
                        to="patients.patient",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations_as_psychologist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta Psicológica",
                "verbose_name_plural": "Consultas Psicológicas",
                "db_table": "psychology_consultation",
                "ordering": ["-consultation_date"],
            },
        ),
        migrations.CreateModel(
            name="PsychologicalAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessment_number", models.CharField(max_length=50, unique=True)),
                (
                    "assessment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("cognitive", "Evaluación Cognitiva"),
                            ("personality", "Evaluación de Personalidad"),
                            ("neuropsychological", "Evaluación Neuropsicológica"),
                            ("vocational", "Evaluación Vocacional"),
                            ("forensic", "Evaluación Forense"),
                            ("clinical", "Evaluación Clínica"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "purpose",
                    models.TextField(verbose_name="Propósito de la evaluación"),
                ),
                (
                    "results_summary",
                    models.TextField(verbose_name="Resumen de resultados"),
                ),
                ("interpretations", models.TextField(verbose_name="Interpretación")),
                ("conclusions", models.TextField(verbose_name="Conclusiones")),
                ("recommendations", models.TextField(verbose_name="Recomendaciones")),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychological_assessments",
                        to="patients.patient",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="psychology.psychologicalconsultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación Psicológica",
                "verbose_name_plural": "Evaluaciones Psicológicas",
                "db_table": "psychology_assessment",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="PsychologicalTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "test_name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la prueba"
                    ),
                ),
                (
                    "test_category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Categoría"
                    ),
                ),
                (
                    "raw_score",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Puntaje bruto"
                    ),
                ),
                (
                    "standardized_score",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Puntaje estandarizado"
                    ),
                ),
                (
                    "percentile",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Percentil"
                    ),
                ),
                ("interpretation", models.TextField(verbose_name="Interpretación")),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="psychology.psychologicalassessment",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tests_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prueba Psicológica",
                "verbose_name_plural": "Pruebas Psicológicas",
                "db_table": "psychology_test",
                "ordering": ["test_name"],
            },
        ),
        migrations.CreateModel(
            name="TherapySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_number", models.CharField(max_length=50, unique=True)),
                (
                    "session_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "session_duration",
                    models.IntegerField(default=60, verbose_name="Duración (minutos)"),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("couple", "Pareja"),
                            ("family", "Familiar"),
                            ("group", "Grupal"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("in_person", "Presencial"),
                            ("virtual", "Virtual"),
                            ("phone", "Telefónica"),
                        ],
                        default="in_person",
                        max_length=20,
                    ),
                ),
                (
                    "presenting_issues",
                    models.TextField(verbose_name="Temas presentados"),
                ),
                (
                    "interventions",
                    models.TextField(verbose_name="Intervenciones realizadas"),
                ),
                (
                    "patient_response",
                    models.TextField(blank=True, verbose_name="Respuesta del paciente"),
                ),
                (
                    "progress_summary",
                    models.TextField(blank=True, verbose_name="Resumen de progreso"),
                ),
                (
                    "goals_addressed",
                    models.TextField(blank=True, verbose_name="Objetivos abordados"),
                ),
                (
                    "homework_assigned",
                    models.TextField(blank=True, verbose_name="Tareas asignadas"),
                ),
                (
                    "homework_completed",
                    models.BooleanField(
                        default=False, verbose_name="Tareas previas completadas"
                    ),
                ),
                (
                    "next_session_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima sesión"
                    ),
                ),
                (
                    "next_session_goals",
                    models.TextField(
                        blank=True, verbose_name="Objetivos próxima sesión"
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programada"),
                            ("completed", "Completada"),
                            ("cancelled", "Cancelada"),
                            ("no_show", "No asistió"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_sessions",
                        to="psychology.psychologicalconsultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="therapy_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="therapy_sessions",
                        to="patients.patient",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions_as_psychologist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión Terapéutica",
                "verbose_name_plural": "Sesiones Terapéuticas",
                "db_table": "psychology_therapy_session",
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_number", models.CharField(max_length=50, unique=True)),
                ("plan_date", models.DateField(default=django.utils.timezone.now)),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha estimada de finalización",
                    ),
                ),
                ("diagnosis", models.TextField(verbose_name="Diagnóstico")),
                (
                    "long_term_goals",
                    models.TextField(verbose_name="Objetivos a largo plazo"),
                ),
                (
                    "short_term_goals",
                    models.TextField(verbose_name="Objetivos a corto plazo"),
                ),
                (
                    "therapeutic_approach",
                    models.CharField(
                        max_length=200, verbose_name="Enfoque terapéutico"
                    ),
                ),
                (
                    "interventions",
                    models.TextField(verbose_name="Intervenciones planificadas"),
                ),
                (
                    "session_frequency",
                    models.CharField(
                        max_length=100, verbose_name="Frecuencia de sesiones"
                    ),
                ),
                (
                    "estimated_sessions",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sesiones estimadas"
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("completed", "Completado"),
                            ("discontinued", "Discontinuado"),
                            ("on_hold", "En pausa"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psychology_treatment_plans",
                        to="core.company",
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_plans",
                        to="psychology.psychologicalconsultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychology_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychology_treatment_plans",
                        to="patients.patient",
                    ),
                ),
                (
                    "psychologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="psychology_plans_as_psychologist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Tratamiento",
                "verbose_name_plural": "Planes de Tratamiento",
                "db_table": "psychology_treatment_plan",
                "ordering": ["-plan_date"],
            },
        ),
        migrations.CreateModel(
            name="ProgressNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "subjective",
                    models.TextField(
                        help_text="Lo que el paciente reporta",
                        verbose_name="Subjetivo (S)",
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        help_text="Observaciones del terapeuta",
                        verbose_name="Objetivo (O)",
                    ),
                ),
                (
                    "assessment",
                    models.TextField(
                        help_text="Interpretación clínica",
                        verbose_name="Evaluación (A)",
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        help_text="Pasos a seguir", verbose_name="Plan (P)"
                    ),
                ),
                (
                    "goals_progress",
                    models.TextField(
                        blank=True, verbose_name="Progreso hacia objetivos"
                    ),
                ),
                (
                    "plan_modifications",
                    models.TextField(blank=True, verbose_name="Modificaciones al plan"),
                ),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_notes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_note",
                        to="psychology.therapysession",
                    ),
                ),
                (
                    "treatment_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_notes",
                        to="psychology.treatmentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Progreso",
                "verbose_name_plural": "Notas de Progreso",
                "db_table": "psychology_progress_note",
                "ordering": ["-note_date"],
            },
        ),
        migrations.DeleteModel(
            name="PsychologyModule",
        ),
    ]
