# Generated by Django 5.1.4 on 2025-10-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardiology", "0001_initial"),
        ("third_parties", "0004_thirdparty_birth_date_thirdparty_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardiologyconsultation",
            name="medical_record",
        ),
        migrations.AlterField(
            model_name="cardiologyconsultation",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cardiology_consultations",
                to="third_parties.thirdparty",
            ),
        ),
        migrations.AlterField(
            model_name="cardiovascularriskassessment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cardiovascular_risk_assessments",
                to="third_parties.thirdparty",
            ),
        ),
        migrations.AlterField(
            model_name="echocardiogram",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="echocardiograms",
                to="third_parties.thirdparty",
            ),
        ),
        migrations.AlterField(
            model_name="electrocardiogram",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="electrocardiograms",
                to="third_parties.thirdparty",
            ),
        ),
        migrations.AlterField(
            model_name="holtermonitoring",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holter_monitorings",
                to="third_parties.thirdparty",
            ),
        ),
        migrations.AlterField(
            model_name="stresstest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stress_tests",
                to="third_parties.thirdparty",
            ),
        ),
    ]
