# Generated by Django 5.1.4 on 2025-09-11 21:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_systemmodule_companymodule_usermodulepermission"),
        ("payroll", "0003_laboratoryspecialty_alter_healthcarerole_category_and_more"),
        ("third_parties", "0004_thirdparty_birth_date_thirdparty_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CUPSCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cups_code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{6}$", "El código CUPS debe tener 6 dígitos"
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descripción completa del procedimiento"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(help_text="Descripción corta", max_length=200),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("consulta", "Consulta Externa"),
                            ("procedimiento", "Procedimiento"),
                            ("cirugia", "Cirugía"),
                            ("laboratorio", "Laboratorio"),
                            ("imagenes", "Imágenes Diagnósticas"),
                            ("rehabilitacion", "Rehabilitación"),
                            ("urgencias", "Urgencias"),
                            ("hospitalizacion", "Hospitalización"),
                            ("ginecologia", "Ginecología y Obstetricia"),
                            ("pediatria", "Pediatría"),
                            ("odontologia", "Odontología"),
                            ("medicina_nuclear", "Medicina Nuclear"),
                            ("patologia", "Patología"),
                            ("otros", "Otros"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("baja", "Baja Complejidad"),
                            ("media", "Media Complejidad"),
                            ("alta", "Alta Complejidad"),
                            ("especial", "Especial"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "specialty_required",
                    models.CharField(
                        blank=True,
                        help_text="Especialidad médica requerida",
                        max_length=50,
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        default=30, help_text="Duración estimada en minutos"
                    ),
                ),
                ("requires_anesthesia", models.BooleanField(default=False)),
                ("requires_hospitalization", models.BooleanField(default=False)),
                ("requires_pre_authorization", models.BooleanField(default=False)),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "professional_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "institutional_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, help_text="Contraindicaciones"),
                ),
                (
                    "preparation_instructions",
                    models.TextField(
                        blank=True, help_text="Instrucciones de preparación"
                    ),
                ),
                (
                    "post_procedure_care",
                    models.TextField(
                        blank=True, help_text="Cuidados post-procedimiento"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Código CUPS",
                "verbose_name_plural": "Códigos CUPS",
                "db_table": "cups_codes",
                "ordering": ["cups_code"],
            },
        ),
        migrations.CreateModel(
            name="MedicalProcedure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("procedure_number", models.CharField(max_length=20, unique=True)),
                ("scheduled_date", models.DateTimeField()),
                ("actual_start_time", models.DateTimeField(blank=True, null=True)),
                ("actual_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Programado"),
                            ("preparing", "Preparando"),
                            ("in_progress", "En Progreso"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                            ("complications", "Con Complicaciones"),
                            ("postponed", "Postergado"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("indication", models.TextField(help_text="Indicación médica")),
                (
                    "pre_procedure_diagnosis",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "post_procedure_diagnosis",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "anesthesia_type",
                    models.CharField(
                        choices=[
                            ("none", "Sin Anestesia"),
                            ("local", "Anestesia Local"),
                            ("regional", "Anestesia Regional"),
                            ("general", "Anestesia General"),
                            ("sedation", "Sedación"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("anesthesia_notes", models.TextField(blank=True)),
                (
                    "procedure_notes",
                    models.TextField(
                        blank=True, help_text="Notas detalladas del procedimiento"
                    ),
                ),
                (
                    "technique_used",
                    models.TextField(blank=True, help_text="Técnica utilizada"),
                ),
                ("findings", models.TextField(blank=True, help_text="Hallazgos")),
                (
                    "complications",
                    models.TextField(blank=True, help_text="Complicaciones"),
                ),
                (
                    "supplies_used",
                    models.JSONField(default=list, help_text="Insumos utilizados"),
                ),
                (
                    "equipment_used",
                    models.JSONField(default=list, help_text="Equipos utilizados"),
                ),
                ("informed_consent_signed", models.BooleanField(default=False)),
                ("consent_signature_date", models.DateTimeField(blank=True, null=True)),
                ("consent_witness", models.CharField(blank=True, max_length=200)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_instructions", models.TextField(blank=True)),
                ("is_billable", models.BooleanField(default=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "insurance_authorization",
                    models.CharField(blank=True, max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anesthesiologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anesthesia_procedures",
                        to="payroll.employee",
                    ),
                ),
                (
                    "assistant_physicians",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assisted_procedures",
                        to="payroll.employee",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedures_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cups_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="medical_procedures.cupscode",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"is_patient": True, "type": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="third_parties.thirdparty",
                    ),
                ),
                (
                    "primary_physician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_procedures",
                        to="payroll.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedures_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Procedimiento Médico",
                "verbose_name_plural": "Procedimientos Médicos",
                "db_table": "medical_procedures",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("pre_procedure", "Pre-procedimiento"),
                            ("during_procedure", "Durante procedimiento"),
                            ("post_procedure", "Post-procedimiento"),
                            ("complications", "Complicaciones"),
                            ("follow_up", "Seguimiento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="procedures/%Y/%m/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to="procedures/thumbnails/%Y/%m/"
                    ),
                ),
                (
                    "capture_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("camera_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_images_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="medical_procedures.medicalprocedure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Procedimiento",
                "verbose_name_plural": "Imágenes de Procedimientos",
                "db_table": "procedure_images",
                "ordering": ["capture_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("abnormal", "Anormal"),
                            ("inconclusive", "No Concluyente"),
                            ("requires_follow_up", "Requiere Seguimiento"),
                        ],
                        max_length=20,
                    ),
                ),
                ("result_summary", models.TextField(help_text="Resumen de resultados")),
                ("detailed_report", models.TextField(help_text="Reporte detallado")),
                (
                    "interpretation",
                    models.TextField(blank=True, help_text="Interpretación médica"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, help_text="Recomendaciones"),
                ),
                ("requires_additional_studies", models.BooleanField(default=False)),
                ("additional_studies_notes", models.TextField(blank=True)),
                ("report_signed", models.BooleanField(default=False)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_results_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedure",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="medical_procedures.medicalprocedure",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Procedimiento",
                "verbose_name_plural": "Resultados de Procedimientos",
                "db_table": "procedure_results",
            },
        ),
        migrations.CreateModel(
            name="ProcedureTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("specialty", models.CharField(max_length=50)),
                (
                    "pre_procedure_template",
                    models.TextField(
                        blank=True, help_text="Plantilla pre-procedimiento"
                    ),
                ),
                (
                    "procedure_notes_template",
                    models.TextField(
                        blank=True, help_text="Plantilla de notas del procedimiento"
                    ),
                ),
                (
                    "post_procedure_template",
                    models.TextField(
                        blank=True, help_text="Plantilla post-procedimiento"
                    ),
                ),
                ("requires_informed_consent", models.BooleanField(default=True)),
                (
                    "required_supplies",
                    models.JSONField(
                        default=list, help_text="Lista de insumos requeridos"
                    ),
                ),
                (
                    "required_equipment",
                    models.JSONField(
                        default=list, help_text="Lista de equipos requeridos"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procedure_templates_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cups_codes",
                    models.ManyToManyField(
                        related_name="templates", to="medical_procedures.cupscode"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Procedimiento",
                "verbose_name_plural": "Plantillas de Procedimientos",
                "db_table": "procedure_templates",
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AddField(
            model_name="medicalprocedure",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medical_procedures.proceduretemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="medicalprocedure",
            unique_together={("company", "procedure_number")},
        ),
    ]
