# Generated by Django 5.1.4 on 2025-09-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("third_parties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdparty",
            name="nombre",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Primer Nombre"
            ),
        ),
        migrations.AddField(
            model_name="thirdparty",
            name="primer_apellido",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Primer Apellido"
            ),
        ),
        migrations.AddField(
            model_name="thirdparty",
            name="razon_social",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Razón Social"
            ),
        ),
        migrations.AddField(
            model_name="thirdparty",
            name="segundo_apellido",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Segundo Apellido"
            ),
        ),
        migrations.AddField(
            model_name="thirdparty",
            name="segundo_nombre",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Segundo Nombre"
            ),
        ),
        migrations.AddField(
            model_name="thirdparty",
            name="tax_code",
            field=models.CharField(
                blank=True,
                help_text="Código tributario: 13 para personas naturales, 31 para jurídicas",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="thirdparty",
            name="address",
            field=models.CharField(max_length=200, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="thirdparty",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Ciudad"),
        ),
        migrations.AlterField(
            model_name="thirdparty",
            name="country",
            field=models.CharField(
                default="Colombia", max_length=100, verbose_name="País"
            ),
        ),
        migrations.AlterField(
            model_name="thirdparty",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="thirdparty",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=100, verbose_name="Barrio"),
        ),
        migrations.AlterField(
            model_name="thirdparty",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Código Postal"
            ),
        ),
        migrations.AlterField(
            model_name="thirdparty",
            name="state",
            field=models.CharField(max_length=100, verbose_name="Departamento"),
        ),
    ]
