# Generated by Django 5.1.4 on 2025-09-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("third_parties", "0002_thirdparty_nombre_thirdparty_primer_apellido_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thirdparty",
            name="is_employee",
        ),
        migrations.RemoveField(
            model_name="thirdpartytype",
            name="is_employee",
        ),
    ]
