# Generated by Django 5.1.4 on 2025-09-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("third_parties", "0003_remove_thirdparty_is_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdparty",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="thirdparty",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                max_length=10,
                verbose_name="Género",
            ),
        ),
    ]
