# Generated by Django 5.1.4 on 2025-10-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("third_parties", "0004_thirdparty_birth_date_thirdparty_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdparty",
            name="is_payer",
            field=models.BooleanField(default=False),
        ),
    ]
