# Generated by Django 4.2.21 on 2025-08-28 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('control_type', models.CharField(choices=[('none', 'Sin Control'), ('receivables', 'Cuentas por Cobrar'), ('payables', 'Cuentas por Pagar'), ('inventory', 'Inventarios'), ('fixed_assets', 'Activos Fijos'), ('bank', 'Bancos'), ('cash', 'Caja'), ('tax', 'Impuestos')], default='none', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_detail', models.BooleanField(default=True, help_text='Permite movimientos directos')),
                ('requires_third_party', models.BooleanField(default=False)),
                ('requires_cost_center', models.BooleanField(default=False)),
                ('requires_project', models.BooleanField(default=False)),
                ('allow_multi_currency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'accounting_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('asset', 'Activo'), ('liability', 'Pasivo'), ('equity', 'Patrimonio'), ('income', 'Ingresos'), ('expense', 'Gastos'), ('cost', 'Costos')], max_length=20)),
                ('nature', models.CharField(choices=[('debit', 'Débito'), ('credit', 'Crédito')], max_length=10)),
                ('is_balance_sheet', models.BooleanField(default=True, help_text='Aparece en balance general')),
                ('is_income_statement', models.BooleanField(default=False, help_text='Aparece en estado de resultados')),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta',
                'verbose_name_plural': 'Tipos de Cuenta',
                'db_table': 'accounting_account_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_budget', models.BooleanField(default=False)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_centers_created', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.costcenter')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'db_table': 'accounting_cost_centers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planificación'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='planning', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'accounting_projects',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sequence_prefix', models.CharField(help_text='Prefijo para numeración', max_length=10)),
                ('next_number', models.IntegerField(default=1)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_accounts', models.ManyToManyField(blank=True, help_text='Cuentas permitidas', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_types', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('default_credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_credit_journals', to='accounting.account')),
                ('default_debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_debit_journals', to='accounting.account')),
            ],
            options={
                'verbose_name': 'Tipo de Diario',
                'verbose_name_plural': 'Tipos de Diario',
                'db_table': 'accounting_journal_types',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('posting_date', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='Referencia externa', max_length=100)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('posted', 'Contabilizado'), ('cancelled', 'Anulado'), ('reversed', 'Reversado')], default='draft', max_length=10)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_value', models.CharField(editable=False, max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('journal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.journaltype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.period')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries_posted', to=settings.AUTH_USER_MODEL)),
                ('reversed_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversing_entries', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'db_table': 'accounting_journal_entries',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('account_code_length', models.IntegerField(default=6, help_text='Longitud del código de cuenta')),
                ('cost_center_required', models.BooleanField(default=False)),
                ('project_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='core.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Cuentas',
                'verbose_name_plural': 'Planes de Cuentas',
                'db_table': 'accounting_chart_of_accounts',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accounttype'),
        ),
        migrations.AddField(
            model_name='account',
            name='chart_of_accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account'),
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.CharField(max_length=200)),
                ('third_party_type', models.CharField(blank=True, choices=[('customer', 'Cliente'), ('supplier', 'Proveedor'), ('employee', 'Empleado'), ('other', 'Otro')], max_length=20)),
                ('third_party_id', models.CharField(blank=True, help_text='ID del tercero', max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=15)),
                ('amount_currency', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('line_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project')),
            ],
            options={
                'verbose_name': 'Línea de Asiento',
                'verbose_name_plural': 'Líneas de Asiento',
                'db_table': 'accounting_journal_entry_lines',
                'ordering': ['journal_entry', 'line_number'],
                'indexes': [models.Index(fields=['account'], name='accounting__account_cbc3e2_idx'), models.Index(fields=['cost_center'], name='accounting__cost_ce_f9ca61_idx'), models.Index(fields=['project'], name='accounting__project_00aa79_idx'), models.Index(fields=['third_party_type', 'third_party_id'], name='accounting__third_p_e0777c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'date'], name='accounting__company_aac23d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['period'], name='accounting__period__7c4b66_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status'], name='accounting__status_037e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['journal_type'], name='accounting__journal_7383db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('company', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['chart_of_accounts', 'code'], name='accounting__chart_o_d4abe0_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='accounting__account_899938_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active', 'is_detail'], name='accounting__is_acti_8819ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('chart_of_accounts', 'code')},
        ),
    ]
