# Generated by Django 4.2.23 on 2025-08-30 05:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='journalentry',
            name='accounting__period__7c4b66_idx',
        ),
        migrations.RemoveIndex(
            model_name='journalentryline',
            name='accounting__third_p_e0777c_idx',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='reversed_entry',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='third_party_type',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='journaltype',
            name='allowed_accounts',
        ),
        migrations.RemoveField(
            model_name='journaltype',
            name='default_credit_account',
        ),
        migrations.RemoveField(
            model_name='journaltype',
            name='default_debit_account',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_balanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='auto_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='hash_value',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='journal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.journaltype'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.period'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('posted', 'Contabilizado'), ('cancelled', 'Cancelado')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='journaltype',
            name='sequence_prefix',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
