# Generated by Django 5.1.4 on 2025-09-11 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0002_remove_journalentry_accounting__period__7c4b66_idx_and_more",
        ),
        ("core", "0002_user_default_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoucherType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("CI", "Comprobante de Ingresos"),
                            ("CE", "Comprobante de Egresos"),
                            ("CG", "Comprobante General"),
                            ("CC", "Comprobante de Contabilidad"),
                            ("CN", "Nota Contable"),
                            ("CB", "Comprobante de Bancos"),
                            ("CA", "Comprobante de Ajustes"),
                            ("CR", "Comprobante de Reversión"),
                            ("CP", "Comprobante de Provisiones"),
                            ("CT", "Comprobante de Traslados"),
                            ("CX", "Comprobante de Causación"),
                            ("CO", "Comprobante de Operaciones"),
                            ("CK", "Comprobante de Cierre"),
                            ("CS", "Comprobante de Saldos"),
                            ("CV", "Comprobante de Ventas"),
                            ("CM", "Comprobante de Compras"),
                            ("CF", "Comprobante de Facturación"),
                            ("CL", "Comprobante de Liquidación"),
                        ],
                        max_length=3,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "prefix",
                    models.CharField(
                        blank=True, help_text="Prefijo del consecutivo", max_length=10
                    ),
                ),
                ("next_number", models.IntegerField(default=1)),
                (
                    "number_length",
                    models.IntegerField(default=6, help_text="Longitud del número"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("auto_post", models.BooleanField(default=False)),
                ("allow_past_dates", models.BooleanField(default=False)),
                ("allow_future_dates", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_types",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Comprobante",
                "verbose_name_plural": "Tipos de Comprobante",
                "db_table": "accounting_voucher_types",
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
    ]
