# Generated by Django 5.1.4 on 2025-09-11 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_vouchertype"),
        ("core", "0003_user_owned_company_alter_user_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="account",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="account",
            name="custom_company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa propietaria de cuenta personalizada (null para PUC estándar)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_custom",
            field=models.BooleanField(
                default=False,
                help_text="True para cuentas personalizadas de empresa, False para PUC estándar colombiano",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="chart_of_accounts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="accounting.chartofaccounts",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["is_custom", "custom_company"],
                name="accounting__is_cust_4d88f3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_custom", False)),
                fields=("code",),
                name="unique_puc_standard_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_custom", True)),
                fields=("custom_company", "code"),
                name="unique_custom_company_code",
            ),
        ),
    ]
